names = ["Tropicacyl", "Sprix", "Compound W", "Myotonachol", "1-Naphline", "Ecortrin", "Celestone", "Eulexin",
         "Timoptic", "Sedatuss", "Sandril", "Versed", "Flugium", "Synthrox", "Asacol", "Cortigel-80", "Piascledine 300",
         "Baroflave", "Sandimmune", "Fungatin", "Aricept", "Mexate", "Metric 21", "Novoridazine", "Maox", "Motrin",
         "Slow Fe", "Hexa-Betalin", "Aerosporin", "Rifadin", "Alermine", "Ormazine", "Gyne-Lotrimin", "Danocrine",
         "Diamox", "Atrovent", "Rhythmin", "Dairyaid", "Stugeron Forte", "Proglycem", "Proferdex", "Vanceril", "Yasmin",
         "Pragestasert", "SK-Lygen", "Hyzyd", "Asthmanefrin", "Ativan", "Mycelex", "D38.5W", "Delsym", "Lasan",
         "Solfoton", "Dialume", "Rolaids", "Doxy-Tabs", "Relefact TRH", "Lact-Easy", "Dalacin", "Kaochlor",
         "Fulvicin-U/F", "Leucomax", "Fer-in-Sol", "Hyprogest", "Aldactone", "Tantum", "Hydromal", "Hydrocortistab",
         "Gluconorm", "Pentam 300", "Simeco", "Depakene", "SK-Dexamethasone", "Arduan", "Mexolone", "Aloquin",
         "Benadryl", "Sulmags", "Tremin", "Tinactin", "Regonol", "Aspirin", "Truphylline", "Klonopin", "Zolpimist",
         "Omnic", "Cystagon", "Theramycin Z", "D.H.E.45", "Dobutrex", "Dexair", "Trymegen", "Suprefact", "Lopurin",
         "Amitril", "Xgeva", "Demo-Cineol", "Asmalix", "Decadron", "Vaniqa", "Isopto Alkaline", "Polycillin", "Hydrate",
         "Dicen", "Lodema", "SK-Furosemide", "Nimbex", "Prostigmin", "Physeptone", "Pariodel", "Chloromycetin",
         "Effexor XR", "Lacrisert", "Celacol HPM", "Largactil", "Pabanol", "Loniten", "Fluocal", "Reminyl", "Milkinol",
         "Sensorcaine", "Natulan", "Dexone", "Desferal Mesylate", "Amodopa Tabs", "Depo-Predate", "Vistacon",
         "Or-Tyl-Protylol", "Broncho-Grippol-DM", "Pharmadine", "Glucamide", "Hurricaine", "I-Pilopine", "Psorigel",
         "Inderal", "Avlosulfon", "Seffin", "Acu-dyne", "Petrogalar Plain", "Dibenzyline", "Sudafed", "Soda Mint",
         "M-Prednisol", "Duphaston", "Pfizerpen", "Cortisporin Suspension", "Florinef", "Duragen", "Marplan",
         "Blenoxane", "Trifluzin", "Furanite", "Uticillin VK", "Myochrysine", "Phenazodine", "Synemol", "C-Long",
         "Fesolfor", "Dilatrate-SR", "Aldomet", "Carbocaine", "Bactroban", "Sotradecol 1%", "Viroptic",
         "Mycifradin Sulfate", "Di-Phen", "Anxanil", "Profilate", "Encaprin", "Delatestryl", "Miacalcin (Salmon)",
         "Delaxin", "Ceptaz", "Anaprox", "Lithonate", "Aluminett", "Valtrex", "AK-Con", "Ergo Caff Tablets", "Insomnal",
         "Mylanta", "Slow-K", "Malarone", "Androcur", "Cellcept", "Nytol with DPH", "Sam-Pam", "Leucogen", "Amcill",
         "Depoject", "Mydrax", "Histray", "Novolin 70/30", "Incivek", "Chorigon", "Oxis", "Vesicare", "Uracel",
         "Glucitol", "Cuprimine", "Ventolin", "Unasyn", "Quelicin", "Lanacillin VK", "Lutrepulse", "Mivaacron", "Sinex",
         "Procalane", "Dihydrergot", "Venalot", "Aquasol A", "Cytoxan", "Oxandrin", "Robafen", "Superchar", "Anestacon",
         "Frisium", "Sporanox", "Baro-CAT", "Aldara", "Debrox Drop", "Isopto Cetamide", "Monistat 3", "Zanaflex",
         "Humira", "Keppra", "IIotycin", "Nervine Nighttime Sleep-Aid", "Dymenate", "Rolisox", "Azalin EC",
         "Prothroplex", "Novotripty", "Nizoral", "Matulane", "Cancidas", "Dopastat", "Prefin Liquifilm", "Orudis-SR",
         "Latropine", "Fenylhist", "Fluor-Op Ophthalmic", "Erycette", "Histopharmin", "Genabid", "Hemocyte",
         "Chlorzine", "Grifulvin V", "Rolazid", "Kidrolase", "Selestoject", "Isocaine HCl", "Trusopt", "Albuteine 25 %",
         "Imdur", "Lioresal", "Nicoderm", "Bretylol", "Pavatym", "Embrocation", "Beconase", "Glaucon", "Arfonad",
         "Folvite", "Sorate", "Kytril", "Akitan", "Ayrsaline", "Fortral", "Triple-Gen Suspension", "Sea-Omega",
         "Prandin", "Anusol-HC", "Nitrofan", "Pancreatin Tablets", "Enlon", "Timecelles", "Adsorbotear",
         "Benadryl Complete allergy", "Humibid L.A", "Konakion", "Koate - HT", "Wellbutrin", "Tearisol", "Aromasin",
         "Meronem", "Di-Azo", "Allerest", "Lo-Quel", "Zomig-ZMT", "Surin", "Achromycin", "Moduretic", "Cialis",
         "PMS Ferrous Sulfate", "Nervocaine", "Robitussin", "Mydriacyl", "Serevent", "Anapolon", "Furamide",
         "Maalox Anti-Diarrheal", "Tears Plus", "Lidopen", "Nordryl", "Vertilox", "Pavatine", "Panwarfin", "Claforan",
         "Aspergum", "Cardizem", "Maxzide", "Diphen", "Clomid", "Tetrex", "Robinul", "Hespan", "Pentasa", "Exjade",
         "Clopra", "Dopamet", "Mediquell", "Taxotere", "Cephulac", "Sk-Amitriptyline", "Phenazine", "Quinora",
         "Virilon", "Delta-D", "Roampicillin", "Cotrim", "Trihexy-2", "Estracon", "Soriatane", "Meladinine", "Iso-bid",
         "Rythmol", "Nitrocotin", "Ferralyn", "Kenalog", "Benoquin", "Pretz", "Advair Diskus", "Protonix I.V.",
         "Propyl", "Furantoin", "Staticin", "Hexastat", "Aludrox", "Syntocinon", "Hydroxal", "Solatene", "Myleran",
         "Tolectin DS", "Cleocin Pediatric", "Coumadin", "Pyroxine", "Ifex", "Doxychel", "Doca Acetate", "Hytuss-2X",
         "Emla", "Claritin", "Benylin DM Cough", "Cafergot Tabs", "Mevinolin", "Plavix", "Cleocin HCl", "Brethine",
         "Chlor-Amine", "FML Liquifilm Ophthalmic", "Bethaprim SS", "Ertaczo", "Sure Lact", "Indocin", "Sandostatin",
         "Gastrografin", "Fertinex", "Synacthen", "Permitil hydrochloride", "Rufen", "Aubagio", "Peptavlon", "Betnesol",
         "Calicylic", "Oreton-Methyl", "Alzapam", "Velban", "Dinate", "Hexadrol", "Albuminar - 5", "Lupron", "Dixarit",
         "Naphcon A", "Maalox", "Pertussin", "DDAVP", "Coricidin Demilets", "Drithocreme", "Max-Caro", "Sulfa-Trip",
         "Medipren", "Madane", "SEROquel", "Penbactam", "Enantone", "Thytropar", "Torecan", "Thioguanine Tabloid",
         "Seromycin", "Dexedrine", "Fototar", "Dristan AF", "Wellcovorin", "Mol-Iron", "Flavorcee", "Fluanxol",
         "Prostin VR Pediatric", "Augmentin", "Cloxapen", "Anergan", "Quinidex Extentabs", "Femazole", "Fluorescite",
         "Protostat", "Furadantin", "Predair-A", "Dramocen", "Temodar", "Microval", "Plasbumin \u2013 5", "Cerezyme",
         "Milk of Magnesia", "Paxil", "Cardi-Omega 3", "Feronim", "Nolvadex", "Protonix", "Pasdium", "Colief", "Frepp",
         "Irodex", "Ritalin SR", "Ivarest", "Prelone", "Sominex formula 2", "Dostinex", "Pentolair", "Antibiopto",
         "Tocopher-Caps", "Fampyra", "Clozaril", "Wyamycin E", "Moclamine", "Fluroplex", "Comfort Eye Drops", "Kefurox",
         "Zonegran", "Dizymes", "CoGentin", "Quiess", "Somophylin-T", "Vasoclear", "Calciday - 667", "Sulfatrim",
         "BuSpar", "Hydrisalic", "Novantrone", "Isopto \u2013 Fenicol", "Daphyne", "Champix", "Naglazyme", "Stabinol",
         "Actos", "Cremacoat 1", "Chloromycetin Palmitate", "Promine", "Dibent", "Promega", "Nor-Mil",
         "Intal Aerosol Spray", "Prozac", "Constant-T", "Cymbalta", "N.T.S", "Enbrel", "Trimox", "Leustatin", "Feosol",
         "Zepine", "Hydrocortone", "Cort", "Mintezol", "Ten-K", "Somophylline", "Intron A", "Dermit", "Fludara",
         "Foradil", "Casodex", "Serpalan", "Anavar", "Lanoxin", "Metronid", "Teebaconin", "Levemir", "Adriamycin",
         "Nitrostat SR", "Depostat", "Vitacarn", "Cellothyl", "Campral", "Ciloxan", "Pulmicort Respules", "Novodipam",
         "Dacodyl Tabs", "Enovil", "I-Methasone", "Durrax", "Cofol", "Adalat", "Trimpex", "Nipride", "Provigil",
         "Ezetichol", "Hepsera", "Dettol", "Losec", "Zaditen", "Prednicen-M", "Murocel Solution", "Nitrolin", "Almox",
         "Daraprim", "Marmine", "Atabrine Hydrochloride", "Accolate", "Sublimaze", "AK-Dilate", "Pavased",
         "Liquifilm forte", "Isopto Tears", "Xenical", "Hydro-Z-50", "Lysodren", "Adsorbocarpine", "Tricor", "Pavagen",
         "Trisenox", "Novomedopa", "Protrin", "Utimox", "E.Pam", "N-Calme", "Nitro Cap", "Sleep-Eze-3", "Urolen Blue",
         "Trecator- SC", "Pyridiate", "Disonate", "Thyracil", "Solu-Medrane", "Lovenox", "Zetia", "Orasone",
         "Humatrope", "Cream", "Buminate 5 %", "Cordaron", "Ceftin", "A.P.L.", "Lonox", "Trihexy-5", "Alveofact",
         "Anectine", "Survanta", "Pen-Vee K", "Dexon", "Isochron", "Neotears", "Furacin", "Zoloft", "Hytrin", "Nuprin",
         "Moebiquin", "Fosamax", "Kefzol", "Prolia", "Kay Ciel", "Hydextran", "Nujol", "Mychel S", "Napamide",
         "Adapettes", "Trasylol", "Cytovene", "Copaxone", "Voltaren(Gel)", "Innovar", "Promapar", "Solu-Medrol",
         "Elase", "Theovent", "Genaspor", "K-Lor", "Voltaren", "Isoptin", "Tylenol", "Monistat 7", "Diahist",
         "Pfizerpen A.S.", "Pediamycin", "Cenafed", "Zyvox", "Duvoid", "Imodium", "Eva Sorbex", "Albenza", "Zerit",
         "Tempra", "DM Cough", "Orajel", "Operand", "Alazine Tabs", "Span-FF", "Penbritin", "ReoPro", "Anadrol",
         "Acthar", "Cytadren", "Nitropress", "Tamofen", "Ircon", "Sereen", "Anectine Flo-Pack", "Penilente", "Osmitrol",
         "Myidone", "Healon", "Difrarel\u2013100", "Cyomin", "Desitin", "Mephyton", "Bretylate", "P.A.S.Sodium",
         "Baciguent", "Ergamisol", "Di-Cyclonex", "Adroyd", "Wigraine Tablets", "Thiosulfin", "AK-Homatropine",
         "Amoxil", "U-cort", "Gamphen", "Bay Progest", "Mylicon", "Solaraze", "Benylin", "Premarin", "Hydroxacen",
         "Hydergine", "NegGram", "Pavulon", "Ipeca", "Suprazine", "Methocel 2%", "Blocadren", "Mesnex", "Breonesin",
         "Allerid O.D.", "Spasmoject", "Selenol", "Ultane", "Feminone", "Tindamax", "Baytussin", "Ziagen", "Primacor",
         "Selsun", "Di-Spaz", "Panasol", "Megace", "Carnitor", "Degest 2", "DHT", "Cremacoat 2", "Cataflam", "Floveat",
         "Donnatal", "Stilphostrol", "FML Forte", "Hyperstat IV", "Condylin", "Indometh", "Wart-Off", "Viterra-E",
         "Difrarel-E", "Difflam", "Suprax", "Charbon", "Plasil", "Lanacort 5", "Eldisine", "Myambutol", "Purinethol",
         "Effient", "UniPen", "Easprin", "Folex", "Diocto", "Rythmodon", "Femguard", "Pradaxa", "Euglucon", "Vermox",
         "Indomed", "Robitet", "Phenergan", "Buffinol", "Tapazole", "Uloric", "Vitamin B-3", "Luvox", "Urabeth",
         "Testrin-P.A.", "Adapin", "Apidra", "Flutex", "Triglide", "Valergen-10", "Android", "Phenoject-50",
         "Dayto Sulf", "Motion-Aid", "Profilnine Heat-Treated", "Travamine", "Bee Six", "Brevibloc", "Hylutin",
         "Gelusil", "Ketalar", "Larinate", "Datril", "Konyne-HT", "ALKa-mints", "Slo-Phyllin", "Zanosar",
         "Haldol Concentrate", "Doxy-100", "Pontacaine HCl", "Micro-K", "Autorix", "Aphrodyne", "Vancocin", "Kwell",
         "Barosperse", "Anthra-Derm", "Fleet Bobylax", "Ritalin", "V.V.S.", "Apo-Sulfatrim", "Titralac.",
         "Crystimin-1000", "Theralax Suppositories", "Latisse", "Depo-Provera", "Sertan", "Diflucan", "Apo-Flurazepam",
         "Hemofil T", "Nulicaine", "Kato", "Kaochlor S-F", "Cortef", "Theo-Dur", "l-Chlor", "Parasal Sodium", "Viranol",
         "Norpace", "Murcil", "Magnevist", "Crestor", "Zorprin", "D60W", "Romazicon", "Synalar", "Pentazine",
         "Hydramine", "Lopid", "Celexa", "Pyridamole", "Ferndex", "Wellferon", "Lomotil", "Neo-Durabolic", "Femiran",
         "Pegasys", "Potasalan", "Geldene", "Risperdal", "Atromid-S", "HP Acthar Gel", "A-Spas", "Roxanol", "Fer-Iron",
         "Depo-Medrone", "E-Mycin E", "Nutrajel", "Phenameth", "Edluar", "T-Stat", "Synandone", "Durabolin", "Stimate",
         "Bepanthene", "Brolene", "Doxinate", "Trobicin", "Ditropan", "Aller-chlor", "Trilafon", "Camptosar", "Pitocin",
         "Desquam - E", "Dantrium", "Amersol", "Requip", "Mazepine", "bromo-seltzer", "Colace", "Azo-Standard",
         "Erythra-Derm", "Biaxin", "Novoferrousulfa", "Phospholine Iodide", "Tagamet", "Lactrase", "Dorcol", "Eskalith",
         "Victrelis", "Prograf", "Tegretol", "Proplex T", "Gemzar", "Neosar", "Depakote", "Nephrox", "Potassine",
         "Nimotop", "Neofed", "Barbito", "Xyloproct", "Yutopar", "HydroDIURIL", "Flind SSD", "Adenocard",
         "Hybolin Decanoate", "Neurontin", "Pabanal", "Evista", "Neut", "Betnelan", "Beldin", "Nitrol", "Bendylate",
         "Glucantime", "Progens Tabs.", "Diprivan", "Humulin 70/30", "Prorex", "Rum-K", "Isopto Frin", "N-G-C",
         "Herceptin", "Pentothal Sodium", "Lithotabs", "Sinemet", "Belara", "Ectosone", "Cortigel-40", "Pepcid",
         "Valdrene", "Novoban", "Penapar VK", "Biotic V Powder", "Aerolate", "Redisol", "Urecholine", "Mozobil",
         "Mistometer", "Durameth", "Temodal", "Piascledine", "Neuropentin", "O-V Statin", "Fenicol", "Ledercillin VK",
         "CeeNU", "Rowasa", "Navane", "Celestone Phosphate", "Ancobon", "Alu-Cap", "Septra", "Koffex", "Betoptic S",
         "Cyclogyl", "Amicar", "Navelbine", "Eldoquin", "Amphojel", "Profasi HP 10", "Hi-Vegi-Lip", "Novodigoxin",
         "Namenda", "Epitrate", "Guiatuss", "Lofibra", "Bioxtra", "Chantix", "Acne Aid", "Neo-Synephrine", "Tysabri",
         "Metandren", "Ocursert Pilo", "Metrodin", "Betalin 12", "Librax", "Mannitol I.V.Injection", "Ultiva",
         "Enseals", "Proxigel", "Uniphyl", "Janimine", "Zinacef", "SK-Hydrochlorothiazide", "Recormon 2000",
         "Americaine", "Nicorette", "Buprenex", "D40W", "Hydrea", "Sirdalud", "Synacthen Retard", "Surmontil",
         "Carvedilol P.S.", "Suprecur", "Tebrazid", "Alphagan", "Moisture Drops", "Depopred", "BiCNU", "Salazopyrine",
         "Phenophen", "Super EPA", "S-T Expectorant", "Inapsine", "Ophthochlor", "Chlor-Mal", "Biodine", "Zyrtec",
         "Protopic", "Sinequan", "Opticrom", "Gleevec", "Korostatin", "Oncaspar", "Pred Mild Ophthalmic", "Rival",
         "Pan Oxyl", "D70W", "Alvesco", "FML S.O.P.", "Aquatar", "Cortenema", "Erymax", "Mycobutin", "Ce-Vi-Sol",
         "Herplex", "Clavulin", "Ectasule Minus", "Topamax", "Provera", "Retet-S", "Ethrane", "Norzine", "Proplex SX-T",
         "Alphacaine", "Edecrin", "Coreg", "Carnitine", "Pitressin Synthetic", "Robamol", "Gastryl", "Dalmane",
         "Sulf-10", "Xolair", "Dermovate", "Epivir", "Neutra-Phos", "Mirapex ER", "Mexitil", "Autrin", "Zovirax",
         "Pantholin", "D50W", "Finevin", "Dioval XX", "Xalatan", "Eloxatin", "Lactaid", "Cetane", "Neo-Cultul",
         "Econochlor", "Slo \u2013fedrin", "Betatrex", "MS Contin", "Novolexin", "Mytelase", "Hetrazan", "Theolair",
         "Amen", "Pennsaid(solution)", "Scabene", "D25W", "Imferon", "Estar", "Rimactane", "T.D.Alermine", "Provigan",
         "Methadose", "Nitoman", "Emitrip", "Cepacol", "Zomig", "Garamycin", "Regitine", "Eldopaque", "Silvadene",
         "Pfizerpen VK", "D20W", "Empirin", "Ango -O- Span", "Ovrette", "Yodoxin", "Pavabid", "Lysedem", "Lucrin",
         "Calmycine", "Arthrotec", "Satric", "Aprozide", "Efedron", "Pantozol", "Myfedrine", "Tums", "Amitriptylene",
         "Demerol", "Fluothane", "Yocon", "Polymox", "Albuminar - 25", "Antizol", "Benylate", "Disotate", "Pergonal",
         "Procan-SR", "SEROquel XR", "Capoten", "Reidamine", "Omnipen", "Sulfa-Gyn", "Thorazine", "Estradiol L.A.",
         "Parnate", "Pipracil", "Vasodilan", "Revlimid", "Clear Eyes", "Septanest SP.", "Crystapen",
         "Plasbumin \u2013 25", "I-Pentolate", "Vasoprine", "Patanase", "Diphenadril", "Alfenta", "Norvasc", "Urodine",
         "Aetrovir", "Antispas", "Omnaris", "Ben-Gay", "Bopen V-K", "Ferrivenin", "Thyro - Block", "Propecia",
         "Micatin", "Fluonid", "A-Methapred", "Sulten-10", "Sustaire", "Chloromycetin Sodium Succinate", "Toradol",
         "Actigall", "Gynogen L.A.20", "Nafcil", "Phazyme", "Balminal D.M", "Dexasone", "Rimso - 50", "Pernavit",
         "Betaseron", "Estinyl", "Reamet", "AK-NaCl", "Aquasol E", "Metryl", "Parvolex", "Baymethazine", "Valium",
         "Ponstan", "Percorten Acetate", "Valcyte", "Alegel", "Sucostrin", "Xeloda", "Hytuss", "Garoin", "Nallpen",
         "Choron Follutein Gonic", "Zosyn", "Orgatrax", "Cafatine Tablets", "Loraz", "Procrit", "Maxipime", "Factorate",
         "Mysoline", "Cetamide", "Apresoline", "Lacril Artificial Tears", "Millazine", "Extencilline 6-3-3",
         "Kandremul Plain", "Phenazin", "Ferrovon", "Microsulfon", "Sulamyd", "Trihexidyl", "Nitroglyn",
         "Phosphate Sandoz", "Grisactin", "Celebrex", "Selukos", "Novoflupam", "Furan", "Robicillin -VK", "Dyazide",
         "Dopar", "S.A.S. 500", "DV", "Bay Bee-12", "Adenoscan", "Hybolin Impreved", "Vistaquel", "Durapam",
         "Nootropil", "Biltricide", "Resyl", "Protral", "Ery-Sol", "Eskalith CR", "Noradryl", "Doxy-200", "Depen",
         "Calcimar (Salmon)", "Cank-aid", "Ketrax", "ChloroFair", "E-Vital", "SK-Pramine", "Stugeron", "ReVia",
         "Tetracyn", "Cafergot", "Astramorph", "Epifrin", "Tracrium", "Dep-Medalone", "Exelon", "Ergomar", "Furoxone",
         "Bricanyl", "Ferrum Hausmann", "Ampyra", "Phenazo", "Zestril", "Rhinocort Aquq", "Amidate", "Polocaine",
         "Zyloprim", "Wigraine", "Pyridium", "Venium", "Dopram", "Malotuss", "Levaquin", "Prothazine", "Indocid",
         "Anafranil", "Razadyne", "Vasotec", "Testred", "Super Totacillin", "BAL in Oil", "Vivox", "Bronkodyl", "Vivol",
         "Kayexalate", "Betapace", "Potachlor", "Isotrate", "Ircon-FA", "Prinivil", "Zocor", "Eurax", "Carafate",
         "Naldecon", "Apo-Keto-E", "Sorbide TD", "Econopred Ophthalmic", "Ludiomil", "Lotrimin", "Almocarpine",
         "Adrucil", "Buminate 25 %", "Betaserc", "Lymphex", "Klorvess", "Mantan", "Minipress", "Zetonna", "Mucomyst",
         "Wycillin", "Vitamin D3", "Nandrobolic", "Rogaine", "Apo-Labetolol", "Betoptic", "Relenza", "Diridone",
         "Meticorten", "Natacyn", "Foillec cort", "Benzac", "Toxogonin", "Gerimal", "Provine Hydrochloride",
         "Chlor-Pro", "Lofene", "Rubramin PC", "Cleocin Phosphate", "Lasix", "Chorex-10", "Rep-Pred", "Floxin",
         "Dritho-Scalp", "Eldepryl", "Telepaque", "Monistat-Derm", "Ticlid", "Retavase", "Naphcon Forte", "Di-Gel",
         "Cerespan", "Gynogen L.A. 10", "Ferfolic", "Ultravist 370", "Pyronium", "Nortussin", "Duracillin A.S.",
         "Xylocaine", "Kenacort", "Virazole", "Mycelex-G", "Cefizox", "Curosurf", "Ephed II", "E.E.S", "Coloxyl",
         "Novafed", "Buscopan", "Apo-Ferrous Sulfate", "Paraplatin", "Keppra XR", "Seldane", "Decaject", "Maxidex",
         "Stoxil Ophthalmic", "Charcoaid", "Cabadon-M", "Cambia", "Cortifoam", "Delestrogen", "Isopto tears",
         "Diphenylan", "Oxsoralen", "Videx", "Vira", "Mebadin", "Phenetron", "Amebaquin", "Baricon", "Kaon-Cl",
         "RemiCade", "camptosar", "Cortrosyn Depot", "Gas- X", "Zoldem", "Erythrocin Lactobionate", "Principen",
         "Lipitor", "Novoquinidine", "Cyclomen", "Isordil", "Testone L.A.", "Gabapentin-Razak", "Avonex", "Compoz",
         "Lunelle", "Elavil", "Fluoderm", "Tazidime", "Daonil", "Andro L.A. 200", "Hexalen", "Reclomide", "Nydrazid",
         "Serepax", "Cleosin T", "PMS Thioridazine", "Transderm-Scop", "Calcijex", "Cortrophin-Zinc", "Novotrimel",
         "Endrate", "Alertec", "Mogadon", "Antepar", "Lodex", "Norisodrine", "Serpanary", "Temovate", "Chorex 5",
         "Chlorspan", "Iosat", "Renvela", "Andolex", "Chloroptic", "Remsed", "Norosemide", "Tenormin", "Uro-Mag",
         "Apo \u2013 Amipi", "Nauseatol", "Zarontin", "Sorbax", "Asthmahaler", "Hep-Lock U/P", "Betaline S",
         "Diamox Sequels", "Azaline", "Pediazole", "Triphasil", "DesOwen", "Elspar", "Bacticort Suspension", "Artane",
         "Laxmel", "Restasis", "Kenacomb", "Glytuss", "Hep-Lock", "Valrelease", "C-Span", "Novolog", "Tums E-X",
         "Gesterol 50", "V-Sol", "Mag-Ox400", "Novodimenate", "Larither", "Valorin", "Muro-128 Ophthalmic",
         "Pronestyl-SR", "Meval", "Transamin", "Mirapex", "Zyvoxam", "Magel", "Vermizine", "Tinaderm", "New-Synephrine",
         "Colrex Expectorant", "Cyanoject", "Norpace CR", "Chlor-Trimeton", "Nebcin", "Aredia", "Ro-Hydrazide",
         "Balminil Expectorant", "Tavist-1", "Intal Nebulizer Sodium", "Intal Powder for Inhalation", "Nitro Cap T.D.",
         "Plaquenil Sulfate", "Rovamycine", "Naprosyn", "Nitrong", "Delta-Cortef", "V-Cillin K", "Vistaject",
         "Ortho Dienstrol", "Diovan", "Curretab", "Natroba", "Nicotinex", "Metandren Ljinguets", "Modecate Decanoate",
         "Levoxine", "Aphen", "Actidose-Aqua", "D5W", "K-Tab", "Floxin Otic", "Betpen-VK", "Retin-A", "Apo-Keto",
         "Potage", "VePesid", "Desonate", "Delfen", "Agoral", "Furalan", "Vitacee", "Diamicron", "Cecon Solution",
         "Bentylol", "Valergen \u201320", "Viagra", "CCNU", "Dramilin", "Robalyn", "Cologel", "Feldene", "Roubac",
         "Viracept", "Zebeta", "Pamelor", "Lipoxide", "Liquifilm Tears", "Norpramin", "Sumycin", "valadol", "Ferriron",
         "Hytakerol", "Tamsover ER", "Oncovin", "Theobid", "Afinitor Disperz", "Depopen 6-3-3", "Glutazone",
         "Fungizone", "AK-Tate", "Endep", "Dulcolax", "Pitressin Tannate in Oil", "Pentamycetin", "Primostat",
         "Lidoject", "Mexihaler-Epi", "Keralyt", "Nutropin", "Lupron Depot", "Dilantin", "Fero-Grad", "Medihaler",
         "I-Prednicet", "Halotussin", "Forane", "Coartem", "Tears Naturale", "Periaction", "Cafetrate Tablets", "Cebid",
         "Trevintix", "Libritabs", "Apo-Dimenhydrinate", "PEG- Intron", "Exosurf Neonatal", "Solage", "Rosalgin",
         "Fotex", "Fero-Gradumet", "Vibal", "Prepopik", "Drithocreme HP 1%", "Hydril", "Flonase", "Tegopen",
         "P.V. Carpine Liquifilm", "Ancef", "Diane", "Dexacen", "Triadapin", "Orap", "Liquaemin Sodium", "Detrositol",
         "Ergostat", "Urinacine", "Kaybovite-1000", "Procardia", "Epsilan-M", "Dramamine", "Everone", "Talwin",
         "Sytobex", "Kabikoinase", "Festal", "Kalcinate", "Teebacin", "Nor-Feron", "Platinol", "Phyllocontin",
         "Depo-Medrol", "Sani-Supp", "Medralone", "Polytar", "Robaxin", "Cobex", "Span-Niacin", "Effexor",
         "Secretin-Ferring", "Cyclocen", "Promaz", "Kabolin", "Tamiflu", "Acticilline", "Isodine", "Suboxone",
         "Tolectin", "Allegra", "Docefrez", "Modalusin", "Azopt", "Albuteine 5 %", "Teldrin", "Oforta", "Avlocardyl",
         "Dairy Ease", "Apo-Ticlopidine", "Cevi-Bid", "Ercatab", "Tambocor", "Factive", "Chlor-Niramine", "Funduscein",
         "Dilocaine", "Iressa", "Dioval", "Neo-DM", "Liquifilm", "Taxol", "Osmoglyn", "Decameth", "Sinufed", "Gelotal",
         "Fortaz", "Pronestyl", "Propanthel", "Neo \u2013 Spec", "Heparin Lock flush", "Panmycin", "Tofranil",
         "RMS Uniserts", "Lo-Trol", "Cortrophin Gel", "Detrol", "AK-Dex", "Artane Sequels", "Ocu-Dex", "Imitrex",
         "Metasep", "Flagyl", "Prostin E2", "Lanvis", "Myciguent", "Cyrin", "Doxy-Lemmon", "Sepp", "Forteo", "Lamictal",
         "Sorbitrate", "Femotrone", "Zortress", "Fragmin", "Zoladex", "Orudis-E", "Nitrostat", "Corticaine", "E.Vista",
         "K-Feron", "Gravol", "Xanax", "Zenapax", "Alimta", "Wehamine", "Trans derm-Nitro", "Gyne-Sulf", "Glycotuss",
         "Azulfidine", "Isonate TR", "Streptase", "Dolophine", "Uritol", "Niclocide", "Reposans-10", "Persantine",
         "Symmetrel", "ISMO", "Pulmicort Turbuhaler", "Mustargen", "Naropin", "Alterna GEL", "Dilomine", "Hal-Chlor",
         "Entrophen", "Dalcaine", "Dalalone", "Ak-Zol", "Benadryl Children\u2019s Allergy", "Metopirone", "Resectisol",
         "Minims-Homatropine", "Bacroban Nasal", "GG \u2013 CEN", "Methopt", "Priscoline", "Glyate", "Prodrox",
         "Serenace", "Rhumacide", "Ak-Tracin", "Novopirocam", "Estraval", "Triostat", "Medrone", "Cin-Quin", "Mestinon",
         "Zyprexa", "Rocaltrol", "Akineton", "Hypotears", "Kwildane", "Hy-gestrone", "Pavarin",
         "Calcium Disodium Versenate", "Desyrel", "Didronel", "Serax", "Proventil", "Pilopin HS", "Epitol",
         "Corgonject-5", "Follistim AQ", "Femara", "Arco -Cee", "Paxil CR", "Prolixin Hydrochloride", "Nystex",
         "Humatin", "Neoquess", "Fibrinogen Human", "Solurex", "DM Syrup", "Off \u2013 Ezy Wart Remover salacid",
         "Antiminth", "Nplate", "Estraguard", "Decadrol", "Nilstat", "Ocu-Pred-A", "Voltaren Ophthalmic", "Baridium",
         "Vevita", "Propulsid", "Bisolvon", "Hycort", "Ak-Sulf Forte", "Lithane", "Omniscan", "Sensipar", "Cortrosyn",
         "Autoplex", "Flomax", "Beta-Val", "Idamycin", "Vaponefrin", "Reactine", "Imfergen", "Hold", "Efodine",
         "Venofer", "Omnipaque", "Atozine", "Novoampicillin", "Akarpine", "Myalgine", "Tusstat", "Xifaxan", "L-Caine",
         "Luminal", "PMS-Dimenhydrinate", "Fumerin", "Pred Forte", "Pregnyl", "Klotrix", "Cyklokapron", "Betaferon",
         "synamol", "Mutamycin", "Fluorosyn", "Questran", "Formulex", "Cytotec", "Sk-Tetracycline", "IC-Green",
         "Wellbutrin SR", "Miochol", "Ercaf Tablets", "Alcopar", "Prometh", "Zymafluor", "Hyperetic", "Sufenta",
         "Deficol", "Exipime", "Rivotril", "Pancreatin Enseals", "Fynext", "Esidrix", "Twilite", "Accutane",
         "Doxy-Caps", "Wymox", "Aventyl", "Librium", "A-D Kaopectate II", "Protopam Chloride", "Zymenol", "CEN-E",
         "Datril-500", "Afinitor", "AmBisome", "Calm X", "Feostat", "Tri- Leven", "Maxalt", "Rapamune", "Mellaril",
         "AK-Nefrin", "Haldol Decanoate", "Antara", "Exsel", "Nix", "Adrenalin Chloride", "Hyzine", "Diabinese",
         "Micronefrin", "Deronil", "Betnovate", "Oxsoralen-Ultra", "DTIC-Dome", "SK-Prednisone", "EryDerm", "Becotide",
         "Emcyt", "Pepto Diarrhea Control", "Pro-Banthine", "Singulair", "Leukeran", "Sulmeprim", "Neulasta",
         "Nasalcrom", "Savlon", "Mabtra", "Mix-tard", "Levophed", "Marcaine", "Glyrol", "Intropin", "Patogestine",
         "Neupogen", "Para-Thor-Mone", "Aralen Phosphate", "Typramine", "Beclovent", "Niloric", "Visipaque", "Somnol",
         "Cemill-500", "Isopto Plain", "Micostatin", "Chlorzide", "Permapen", "AK-Pentolate", "Merrem", "Andryl",
         "Ascorbicap", "Lamprene", "Androlone", "Norpanth", "Trysul", "Rhodis", "Panthoderm", "Pheryl-E 400",
         "Cogespirin", "Sonata", "Nicobion", "Onoton", "Humafac", "ACTH Gel", "Aggrastat", "Tarceva", "D30W",
         "Lifocort", "Vistazine", "Cutivate", "Calcibind", "Isuprel", "Trihexane", "Betadine", "Valisone",
         "Ultravist 300", "Triacet", "Actimmune", "Reglan", "Berubigen", "Sulfamylon", "Sorbitrate SA", "Amoline",
         "Alupent", "Mevacor", "Nicobid", "Methidate", "Yohimex", "Mydfrin", "Fluolar", "Imuran", "Cipro", "Polydine",
         "Larodopa", "Theoclear", "Klor-Con", "Levate", "Trandate", "Excedrin", "Lytears", "Cortaid", "Ferfol",
         "Tensilon", "Atarax", "Methergine", "Indo-Lemmon", "Ultram", "Ceporex", "Niac", "Simulect", "Spasmoban",
         "Vermizol", "Salinex", "Zithromax", "Januvia", "Diaqua", "Gee \u2013 Gee", "Prepidil", "Prolixin", "R-Gene 10",
         "Septanest N", "Provatene", "Tazicef", "Fumasorb", "Renografin", "Fybogel Mebeverine", "Eprolin Gelseals",
         "Tavist", "Celestone Soluspan", "Aristocort", "Mykinac", "Referon-A", "Pedia Care 1", "Theospan-SR",
         "Citanest", "Verdeso", "Lopressor", "Minilyn", "AK-Mycin", "D1OW", "Paverolan", "K-Phos", "Calde",
         "Asmanex Twisthaler", "Dimentabs", "Isopto Homatropine", "Ergotamine", "Depakote ER", "Metaprel", "Decofed",
         "Capastat Sulfate", "Alkeran", "Catapres", "Proloprim", "Mevaril", "Normodyne", "Oretic", "Sonazine", "Azelex",
         "Sucrets Cough Control", "Synthroid", "Crysticillin A.S.", "Lomanate", "Precedex", "Diphenatol", "Avelox",
         "Biosone", "Precose", "Lariam", "Frezone", "Muro Tears Solution", "Lisinoraz", "Hematran", "Injectafer",
         "Rituxan", "SPS", "Cytomel", "Aqua MEPHYTON", "Vibra-Tabs", "Chealamide", "Progestaject-50", "Deca -Durabolin",
         "Cozzar", "Deep Healing Rub", "Vanquin", "Chronodose", "Mucosol", "I-Homatrine", "Byclomine", "Laniazid",
         "Ambien", "Bronitin Mist", "Vicks Va-tro-nol", "Gilenya", "Dovonex", "E-Ferol", "Eprex", "Robidex", "Efudex",
         "NovoNorm", "Vumon", "Biscolax", "Victoza", "Zeroxin- 5", "Toprol XL", "Calamox", "Unifer", "Zofran", "Dull-C",
         "Viscerol", "Viramune", "Tasigna", "Ventolin Inhaler", "Stilamin", "Rocephin", "Chemet", "Bicillin L-A",
         "Tevagestine", "Narcan", "Modapril", "Trental", "Cena-K", "Bentyl", "Cemill-1000", "Serophene",
         "Isopto Carpine", "Albalon Liquifilm", "Gordofilm", "Anabolin-l.M", "Zantac", "D2.5W", "Finacea", "Bactrim",
         "Duralone", "Amitone", "Chronulac", "Ful-Glo", "Calan", "Mallergan", "Cibacalcin (human)", "Pima", "Acephen",
         "Pro-defalgan", "Dommanate", "Monocor", "Cevalin", "Anti-tuss", "Cervidil", "Cytosar-U", "Vancenase",
         "Stelazine", "Amvisc", "Zipsor", "Lomine", "Nitrospan", "Sutent", "Afrinol", "Keflin", "Vasocon", "Ponstel",
         "Thor-Prom", "Epogen", "Measurin", "Lithobid", "Salivar", "Advil", "Keflex", "Dramoject", "Cerubidine",
         "Cyclopar", "Corisan", "Gly-Oxide Liquid", "Levothyroid", "Syroxine", "Isovue", "Cosmegen", "Decapeptyl",
         "Alu-Tab", "Lantus", "SMZ-TMP", "Veetids", "Citrucel", "K-Dur", "Pilokair", "Valzar", "Trileptal",
         "Abbokinase", "Campath", "Fluor-I-Strip A.T.", "Honvol", "Gonal-F", "Cortalone", "Proscar", "Amikin",
         "Lamisil", "MonoKet", "Renagel", "Anacin-3", "Duramorph", "Prelestone", "Akne-Mycin", "Theophyl", "Nitro-Bid",
         "Serpate", "trendar", "Rubesol-1000", "Colifoam", "Sofarin", "Slo-Salt", "Vibramycin", "Haldol"]
