products = [
  "Nasal Spray:\t۲۰ mg/ml",
  "For Injection: Penicillin G \t۵۰۰۰۰۰۰ Units/Vial (as Sodium Salt)",
  "For Injection: \t۴۴۰ mg/Vial",
  "Coated Tablets or Tablets:\t۳ mg (as ۲HCl)",
  "Topical Solution:\t۴%",
  "Infusion: \t۵ %",
  "Ammonium Chloride\t۱۲۵ mg/۵ ml and",
  "Scored Tablets:\t۵۰ mcg",
  "مقدار ۱.۳۸g کلرامفنیکل سدیم سوکسینات، تقریباً معادل ۱g کلرامفنیکل است.",
  "Vitamin D\t۵۰۰ I.U. and",
  "Capsules:\t۱۵ mg",
  "Injection:\t۲۰ mg/ml (as Decanoate)",
  "Topical Gel:\t۰.۷۵%",
  "Trisodium Citrate, ۲H۲O\t۲.۹ g and",
  "Coated Tablets or Tablets:\t۰.۵ mg (as ۲HCl)",
  "Powder for Suspension:\t۴۵۴ g",
  "Tablets:\t۲۰۰mg",
  "Capsules or Tablets: Cloxacillin \t۲۵۰ mg",
  "Injection: Metoclopramide \t۱۰ mg/۲ ml",
  "Injection:\t۵۰۰۰ U/ml",
  "Capsules:\t۱۵۰ mg",
  "MgO\t۳۰ mg and",
  "Tablets: Leucovorin Ca \t۱۵ mg",
  "Capsules:\t۲۵۰ mg",
  "Syrup:\t\t۲۰۰ mg/۵ ml (as HCl)",
  "Implant: ۳.۶ mg",
  "Sterile Eye Drops:\t۰.۱۰%",
  "For Injection:\t۱۰۰ Units",
  "Paraaminobenzoic Acid\t۵% W/W and",
  "For Oral Suspension:\t۱۲۵ mg/Sachet",
  "Injection: \t۶۰۰ IU/ml (۰.۵ ml)",
  "Lotion: \t۲۵% (۲۵۰ ml)",
  "Injection:\t۱/۶ Molar",
  " Tablets:",
  "Zinc Sulfate\t۱.۵ g and",
  "Topical Gel:",
  "Delayed Release Tablets:\t۵۰۰ mg",
  "For Injection:\t۱۰ mg",
  "For Injection: \t۲۵ mg/Vial (۱۰ ml)",
  "Pyrazinamide\t۳۰۰ mg and",
  "Injection:\t۱g/۵ml",
  "Topical Ointment: Clobetasol \t۰.۰۵% (۱۰۰, ۲۰۰g)",
  "Infusion:\t۲۰%",
  "For Infusion:\t۲۰۰ U/Vial",
  "Ferrous:\t۶۰ mg (as Sulfate) and",
  "Topical Ointment: \t۵%",
  "Injection Solution:\t۵۰۰۰۰ U/ml",
  "Tablets: ۲.۵ mg",
  "Topical Lotion:",
  "Syrup:\t Midazolam HCl \t۲ mg/ml",
  "Na+\t۱۳۰ mEq/Lit and",
  "Injection:\t۰.۵ mg/۱ml",
  "Lidocaine HCl\t۲% (۲۰ mg/ml) and",
  "Cartridge (Carpool):\t۲% (as HCl)",
  "Chewable Tablets:\t۲۵۰ mg (as ۳H۲o)",
  "Injection:\t۴ mg/۲ ml",
  "Clavulanic Acid \t۶۲.۵ mg/۵ ml (as Potassium Salt)",
  "Sterile solution for Intraocular Use:\t۲%",
  "Injection:\t۱۰۰ mg/ml (۵,۱۰ ml)",
  "Tablets:\t\t ۳۰ mg",
  "Injection:\t۲۵ mg/۲ ml",
  "Elixir:\t\t۰.۵ mg/۵ ml",
  "Syrup:\t\t۲۰۰ mg (۴۰ mg Iron) /۵ ml",
  "Oral Drops:\t۰.۵ mg/ml",
  "Tablets:\t۱ mg",
  "Solution For Inhalation:\t۵ mg / ml (as Sulfate)",
  "Shampoo:\t۲%",
  "For I.V.Infusion:\t۲۰%",
  "Liquid For Topical-Oral:\t۱۰% (۱۵ ml)",
  "Injection:\t۱۰۰ mg/ml (۱۰ ml)",
  "Coated Tablets: Fluphenazine ۲HCL\t۲.۵ mg",
  "Tablets: \t۳۰۰ mg",
  "Injection (Suspension):\t۴۰ mg/ml",
  "Powder:\t۵۰۰ mg/Sachet",
  "Extended-release tablets: ۱۰ mg",
  "Injection:\t۱۰۰۰۰ U/ml",
  "Lotion: Diethyltoluamide\t۳۰-۴۰%",
  "Brompheniramine Maleate\t۱۲ mg and",
  "For Injection:\t۱۲ I.U./Vial",
  "Injection Solution:\t۵۰ mg/ml",
  "Injection: \t۳۰۰ mgI/ml (۲۰ml, ۵۰ml, ۱۰۰ml)",
  "Oral Drops:\t۵۰ I.U./ml",
  "Delayed Release Capsules: \t۱۵ mg (as Sodium Sesquihydrate)",
  "Tablets:\t \t۱ mg",
  "Vitamin B۱\t۱.۲۵ mg and",
  "(۷۰% Isophane Insulin + ۳۰% Insulin Injection)",
  "Sustained Release Tablets:\t۷۵ mg",
  "Chlorpheniramine Maleate\t۰.۵ mg/۵ ml and",
  "Disinfection solution:\t۳۰% ( W/W H۲O۲ )",
  "Concentrate For Infusion:\t۲۵ mg/۵ ml",
  "Caffeine\t۱۰۰ mg",
  "Capsules: ۱۰ mg",
  "Injection:\t۳۰۰ mcg/ml",
  "For Injection:\t۱ mg/Vial",
  "Sterile Ophthalmic Solution I:\t۴۸۰ ml",
  "Tablets:\t۱۰۰ mcg",
  "NaH۲Po۴\t۱۹۳۶ mg and",
  "◇ Tablets:\t۲۰ mg",
  "Co- Amoxiclav ۴۵۷",
  "For Injection:\t۲ g/Vial+Diluent",
  "Extended-Release Tablets: ۳۰۰ mg (as Fumarat)",
  "Scored Tablets:\t۳۲۵ mg",
  "Intratracheal Suspension:\t۱۰۸ mg/۱۰ ml Vial",
  "For Injection:\t۲ mg/Vial",
  "Hydrochlorothiazide\t۵۰ mg",
  "Penicillin G Benzathine\t۶۰۰۰۰۰ Units/Vial and",
  "Sublingual Tablets:\t۲ mg",
  "◇ For Suspension:\t۱۰۰ mg/Sachet",
  "Tablets:  ۳۰۰ mg",
  "Enema or Suppositories:\t۴ g/۶۰ ml",
  "Chlorpheniramine Maleate\t۰.۵ mg and",
  "Syrup:\t\t۲ mg/ ۵ ml (as Sulfate)",
  "◇Film Coated Tablets:\t۵ mg",
  "Injection:\t۵۰ mg/ml",
  "Injection:\t۱۰۰ mg/ml (۰.۲,۰.۴,۰.۶,۰.۸,۱ ml)",
  "For Oral Suspension:\t۲۵۰ mg/۵ml (۱۰۰ml)",
  "Topical Cream:\t۰.۰۵%",
  "Oral Drops:\t۱۵۳ mg/ml",
  "For Injection:\t۳.۷۵ mg",
  "Injection:\t۱۰۰ mg/۵ ml",
  "Vitamin B۱۲\t۰.۵ mcg and",
  "◇ Film Coated Tablets:\t۶۰۰ mg",
  "Sulfadoxine\t۵۰۰ mg and",
  "Scored Film Coated Tablets:\t۴ mg",
  "Sublingual Tablets or Capsules:\t۲.۶ mg",
  "Epinephrine (Bitartrate)\t۵ mcg/ml",
  "Infusion:\t۲۰۰ mg/۱۰۰ ml (as Lactate)",
  "Concentrated Comphor Water\t۲.۵ ml",
  "Injection:\t۵۰۰۰ I.U./ml",
  "Vitamin D\t۴۰۰ I.U./ml",
  "Chloroguanide\t۲۵ mg",
  "Pediatric Suppositories:\t۷.۵ mg",
  "Enteric Coated Tablets:\t۵۰ mg",
  "Tablets: Leucovorin Ca \t۲۵ mg",
  "Injection:\t۲ mg /۲ ml",
  "Coated Tablets: Chloroquine \t۵۰ mg (as Phosphate)",
  "BULK (Phosphate, Sodium Monobasic) (NaH۲PO۴)",
  "Scored Coated Tablets:\t۲۵ mg",
  "Suspension for Nebulisation:\t۱ mg/۲ ml",
  "Mouth Wash:\t۰.۲% w/V",
  "Vaginal Cream:\t۰.۶۲۵ mg/g",
  "For Injection: \t۳۷۵۰IU/Vial",
  "Ipratropium Bromide\t۲۰ mcg/Dose and",
  "Coated Tablets:\t۵۰۰۰۰۰ Units",
  "Infusion:\t۵۰۰ ml",
  "Sterile Eye Drops:\t۰.۵%",
  "Injection Solution:\t۵ mg/ml",
  "I.V.Injection:\t۲%(۵ml)",
  "Sustained Release Coated Tablets:\t۱۲۰ mg",
  "Injection:\t۰.۵% (۱۰,۲۰ ml)",
  "For Injection:\t۱۰۰۰۰ I.U.",
  "Lotion:",
  "Topical Solution:",
  "For Injection:\tMethotrexate* \t۵۰ mg (as Sodium Salt)",
  "Injection:\t۳۰۰ mg/۱۰ ml",
  "Topical Ointment:",
  "Spray \t\t۲۵۰ mcg/ Dose",
  "Sustained Release Tablets:\t۲۵۰ mg",
  "Coated Tablets:\t۵ mg",
  "Tablets:\t۳۰ mg",
  "Capsules:\tEq. To ۱۰۰ mg Fe++",
  "For Injection: Cloxacillin \t۱g/Vial",
  "NaCl\t۰.۶۴% or ۰.۴۹%",
  "Injection Solution:\t۲۵ mg/۱ ml",
  "Vaginal Tablets:\t۱۰۰۰۰۰ Units",
  "Extended-Release Tablets: ۵۰ mg (as Pamoat)",
  "For Injection: ۲۰ mg/vial",
  "Injection:\t۵۰ mg/۱ ml",
  "مقدار ۱.۰۵g سفازولین سدیم، تقریباً معادل ۱g سفازولین است.",
  "مقدار ۱.۰۹g کلیندامایسین هیدروکلراید، تقریباً معادل ۱g کلیندامایسین است.",
  "Hydrochlorothiazide\t۲۵ mg",
  "◇ Tablets:\t۱۰ mg",
  "Vaginal Gel:\t۱ mg/۲.۵ ml",
  "◇ Tablets:\t۱۰ mEq",
  "مقدار ۱.۱۷g اریترومایسین اتیل‌سوکسینات تقریباً معادل ۱g اریترومایسین است.",
  "Injection: \t۱۰ mg/ml (۱۰ml, ۵۰ml)",
  "Capsules: Doxycycline \t۱۰۰ mg (as Monohydrate)",
  "Injection: Amikacin \t۵۰۰mg/۲ml",
  "Oral Suspension: Pyrvinium\t ۵۰ mg/۵ ml",
  "Injection:\t۲۵۰ mg/ml (۱۰ml)",
  "Lotion Shampoo:\t۲%",
  "Cartridge (Carpool):",
  "Prilocaine\t۲.۵%",
  "Aerosol:\t۱۰۰ mcg / Dose (۲۰۰ Doses)",
  "Suspension for Nebulisation:\t۰.۵ mg/۲ ml",
  "Film Coated Tablets:\t۲۵۰ mg",
  "For Injection:\t۲۵۰ U/Vial + Diluent",
  "Injection:\t۳%",
  "Injection: Trifluoprazine \t۱ mg/ml",
  "◇ Patch:\t۱۵ mg/۲۴ h",
  "Co- Amoxiclav ۶۲۵",
  "Beclomethasone Dipropionate\t۵۰ mcg/Dose",
  "Injection\t۱۰۰ IU/ml (۳,۱۰ ml)",
  "Tablets:\t۲۵ mg",
  "Injection:\t۷۵ mg/۳ ml",
  "Ophthalmic Ointment:",
  "Vitamin E\t۱۰ mg and",
  "Pediatric Suppositories:\t۱۲۵ mg",
  "Inhalation capsules:\t۲۰ mg",
  "Sterile Eye Drops:\t۳ mg/ml",
  "Chlorpheniramine Maleate\t۲ mg",
  "Capsules: Paromomycin \t۲۵۰ mg",
  "Injection Solution:\t۲% (۲۰ml)",
  "For Injection:\t۱۵۰۰ Units",
  "Fluticason Propionate \t۲۵۰ mcg",
  "Sublingual Tablets:",
  "For Injection: Acyclovir \t۲۵۰ mg/ml (as Sodium Salt)",
  "Scored Tablets: Levamisole \t۵۰ mg (as HCl)",
  "Liquid:\t۳۰ mg/۵ ml",
  "For Oral Suspension: \t۲۰۰۰۰۰ I.U/۵ ml (as Benzathine)",
  "Tablets:\t۲۵۰ mg (as Dihydrate)",
  "Betamethasone Dipropionate\t۰.۰۵%",
  "Delayed Release Capsules: ۳۰ mg",
  "Capsules:\t۰.۲۵ mcg",
  "هر I.U. تقریباً معادل ۰.۳۳mg سوماتروپین است.",
  "Carpool:",
  "Powder for Inhalation:\t۱۰۰ mcg/Inhalation",
  "For I.V.Injection:\t۵۰۰۰۰۰ Units/Vial",
  "For Injection: Streptomycin \t۱ g/Vial",
  "Diphehydramine HCl\t۱۲.۵ mg/۵ ml and",
  "Injection Solution: ۶ mg/ mL",
  "Cyproterone Acetate\t۲ mg and",
  "Enema:",
  "Capsules or Coated Chewable Tablets:\t۲۵۰۰۰ U.",
  "ویتامین K۱ (فیتونادیون)، شکل صناعی محلول در چربی ویتامین K است.",
  "Topical Solution:\t۵۰ mg/ml",
  "Chloroguanide\t۱۰۰ mg",
  "NaCl\t۷.۴۴ mg",
  "Docusate Na \t۰.۰۱g and",
  "Injection:\t۱۰۰ mg/ml (۵ ml)",
  "Piperacillin\t۲ g (as Sodium Salt) and",
  "Capsules:\t۱ mg",
  "Sterile solution for Eye Use:\t۲%",
  "KCl\t۰.۳۹۵ mg",
  "Injection:\t۴۰ mg/ml",
  "Oral Solution:\t۳۰۰ mgI/ml",
  "Injection:",
  "Lotion Shampoo:\t۱%",
  "For Injection:\t۳۰ mcg (۶ million I.U.)/Vial",
  "Syrup:\t\t۲ mg/۵ ml",
  "Tablets:\t۰.۵ mg",
  "Coated Tablets:\t۴۰۰ mg",
  "Injection:\t۱ mg/ml (۲,۵,۱۰ ml)",
  "Ampules for Inhalation:\t۰.۳ ml",
  "Topical Cream:\t۱۰ mg/g (۵۰, ۵۰۰ g)",
  "Vaginal Gel:\t۰.۷۵%",
  "Na۲MoO۴ ۲H۲O\t۰.۲۵ mg and",
  "For Injection:\tCefazolin ۲۵۰ mg/Vial",
  "I.V. Injection:\t۵۰ mcg/۱۰ ml",
  "Tablets: ۰.۷۵ mg",
  "Injection:\t۵ million I.U./ml",
  "Coated Tablets: Biperiden HCl SR\t۴ mg",
  "For Injection:\t۵۰۰ mg",
  "Viscous Solution:\t۲% (as HCl)",
  "Gelatin Succinylated\t۴۰g (۴%) and",
  "Injection:\t ۲۰۰ mg/ml",
  "Sustained Release Tablets:\t۱۵۰ mg",
  "Dextrose Anhydrous\t۲۰ g",
  "Microcoated Tablets:\t۱۰۰ mg",
  "Na Acetate, ۳H۲O\t۰.۳۹%",
  "Oral Drops:\t۴۰ mg/ml",
  "Tablets:\t \t۱۶۰ mg",
  "For Injection: \t۴۰۰ mg/Vial",
  "Pancreatin\t* and",
  "Desogestrel\t۰.۱۵ mg and",
  "Drospirenone \t۳ mg and",
  "Powder:\t۳ g/sachet",
  "Capsules: \t۱۰ mg",
  "Tablets:  ۳۲۰ mg",
  "۷: Ferrous Sulfate or Fumarate\t۲۴.۶۵ mg (Iron)",
  "Liquid:\t۳۳.۳۳%",
  "* with and without preservative",
  "◇ Patch:\t۱ mg/۷۲ h",
  "Eye Drops:\t۰.۲۰%",
  "Extended-release capsules:  ۱۵۰ mg",
  "Injection:\t۳۰۰ mg I/ml (۱۰, ۲۰, ۵۰ ml)",
  "Iron Sulfate ۷H۲O\t۵۰ mg",
  "For Injection:\t۷۰ mg/Vial",
  "Calcium Carbonate\t۰.۳ g",
  "Macrogol ۳۳۵۰\t۱۳.۱۲۵ g and",
  "For Injection:\t۱۰ U/Vial",
  "Oral Suspension:\t۱۲۰ mg/۵ ml",
  "Zinc\t۰.۱۲۵ mg and",
  "Tazobactam\t۲۵۰ mg (as Sodium Salt)",
  "For Injection:\t۲۵۰ U/Vial",
  "Tablets:\t۸ mg",
  "Cl -\t۱۵۶ mEq/Lit",
  "Scored Tablets:\t۵۰ mg",
  "Film Coated Tablets: \t۴ mg",
  "Oral Drops:\t۵۰۰۰۰ I.U./ml (۱۰ ml)",
  "Syrup:\t\t۵۰ mg/۵ ml",
  "Solution For Nebulisation",
  "Injection:\t۱ g/۱۰ ml",
  "For Injection:\t۵۰۰ Units",
  "Tablets: ۲۵ mg (as Fumarat)",
  "◇ Film Coated Tablets:\t۳۰۰ mg",
  "Vitamin E\t۲.۵ I.U. and",
  "Codeine phosphate\t۲۰ mg",
  "Vaginal Suppositories:\t۴۰۰ mg",
  "Tablets: ۲۰۰ mg",
  "Tablets: Leucovorin Ca \t۵ mg",
  "Dexpanthenol\t۱۰ mg and",
  "CuSO۴ ۵H۲O\t۳.۹ mg and",
  "Ophthalmic Ointment:\t۳ mg/g",
  "For Injection:\t۱ mg",
  "Intra Nasal Solution:\t۰.۱ mg/ml",
  "Injection:\t۲۵ mg/۲.۵ ml",
  "Chewable Gum:\t۲ mg",
  "Scored Coated Tablets:",
  "Syrup:\t\t۱۰۰ mg/۵ ml (۶۰ ml)",
  "Gel",
  "Infusion:\t۱۰%",
  "For Injection: Acetazolamide \t۵۰۰ mg/Vial (as Sodium Salt)",
  " For Injection:\t۵۰۰ mg/Vial (as Trihydrate)",
  "Tablets: \t۵۰۰ mg",
  "Injection:\t۱۵ mcg/ml",
  "Tablets:\t۵۰۰ mg",
  "Phenobarbital\t۵۰ mg",
  "Amoxicillin\t۲۵۰ mg/Sachet (as Trihydrate) and",
  "Film Coated Tablets:\t۵ mg",
  "Pediatric Drops:\t۱۰۰ mg/ml",
  "Injection: \t۷۵ IU",
  "Tablets or Capsules:\t۲۵۰ mg",
  "Enteric Coated Tablets:",
  "Guaifenesin\t۱۰۰ mg/۵ ml and",
  "Enteric Coated Tablets:\t۳۲۵ mg",
  "Scored Tablets (Forte):",
  "For Injection:\t۱g",
  "مقدار ۲۶۱mg کلرامفنیکل پالمیتات، تقریباً معادل ۱۵۰mg کلرامفنیکل است.",
  "Penicillin G Potassium\t۳۰۰۰۰۰ Units/Vial and",
  "Film Coated Tablets: \t۲۰۰ mg",
  "Injection:\t۶.۵ mg/ml",
  "Betamethasone Acetate \t۳ mg/ml and",
  "Injection:\t۰.۱۰%",
  "Diphenoxylate HCl\t۲.۵ mg and",
  "Tablets:\t۴۰۰ mg",
  "Infusion:\t۲۰ % (۵۰ ml)",
  "Injection:\t۵۰ mg/ml (۲, ۱۰ ml)",
  "Vitamin C\t۱۵۰ mg and",
  "Topical Ointment: Triamcinolone\t۰.۱%",
  "Injection Solution:\t۱۰ mg / ۰.۵ ml (۰.۵ و ۱و ۱۰ ml)",
  "Syrup: Piperazine Hydrate \t۷۵۰ mg/۵ ml (as Citrate)",
  "Tablets:\t۲۰ mg",
  "Film Coated Tablets or Capsules: Nortriptyline \t۱۰ mg",
  "Susppositories:\t۲۰ mg",
  "Powder for Inhalation: \t۲۰۰ mcg/Inhalation",
  "Enteric Coated Tablets:\t۲۵ mg",
  "* Dextrose anhydrous or monohydrate",
  "Injection:\t۵ mg/۱ ml (as HCl)",
  "Sterile Ophthalmic-Otic Drops:\t۰.۱% (as Disodium Salt)",
  "Injection:\t۱۰۰ USP U/ml",
  "For Infusion:\t۶%",
  "Topical Gel:\t۰.۰۳%",
  "Oral Solution: ۱۰۰ mg/mL",
  "Penicillin G Procaine\t۳۰۰۰۰۰ Units/Vial)",
  "For Injection:\t۱.۵ g",
  "Injection:\t۱ mg/۰.۵ ml",
  "Ergotamine\t۲ mg and",
  "Tablets:\t۴۰ mg",
  "Sublingual Tablets or Capsules:\t۶.۴ mg",
  "Shampoo:\t۷.۵% (۱۴۰ ml)",
  "Mn\t۰.۵ mg and",
  "Ophthalmic Ointment:\t۵۰۰ U/g",
  "Solution for Injection:  ۲ mg/ml",
  "Injection: Chloroquine\t۲۵۰ mg/۵ ml (as Sulfate)",
  "Sustained Release Capsules or Tablets:\t۱۰۰ mg",
  "Vaginal Cream:\t۵%",
  "For Injection:\t۲ mg",
  "Topical Solution:\t۲۰ mg/ml",
  "Film Coated Scored Tablets:\t۶۰ mg",
  "Injection:\t۱۰۰ mcg/ml",
  "Coated Tablets:\t۸۰ mg",
  "Syrup:\t Chloroquine \t۵۰ mg/۵ ml (as Sulfate)",
  "Film coated Tablets: \t۵۰۰ mg",
  "Scored Film Coated Tablets:\t۸۰۰ mg",
  "For Injection:\t۱g/Vial",
  "Phenyl Propanolamine HCl\t۵ mg/۵ ml (۶۰ ml)",
  "tables",
  "Ferrous Fumarate\t۳۵۰ mg and",
  "A.S.A\t۳۲۵ mg and",
  "BULK (Phosphate, Potassium Monobasic) (KH۲PO۴)",
  "Coated Tablets:\t۲۰۰ mg",
  "Coated Tablets:\t۸ mg",
  "Oral Solution:\t۷۶%",
  "Topical Ointment:\t۳%",
  "Coal Tar Extract\t۵% and",
  "Sterile Eye Drops:\t۲۰%",
  "Lotion:\t\t۵%",
  "Oral Solution:\t۱۰۰ mg/ml",
  "Injection:\t۱۰۰ I.U./ml",
  "Injection (Multi-dose cartridge):  ۸۳۳ IU/vial",
  "Amoxicillin\t۵۰۰ mg (as Trihydrate) and",
  "Lyophilized Powder for IV Infusion:  ۵۰۰ mg/vial",
  "For Injection: Ampicillin\t۲۵۰ mg/ Vial (as Sodium Salt)",
  "Oral Suspension: Metronidazole \t۱۲۵ mg/۵ ml (as Benzoate)",
  "Chewable Tablets:\t۱g",
  "For Injection:\t۷۵۰۰۰۰ I.U./Vial",
  "Plaster:\t۱۰ mg/۲۴ h",
  "Injection Solution: ۲۵ mg/mL",
  "For Injection:\t۳۰۰ mg",
  "Ovule:\t\t۵۰۰ mg",
  "Injection: Ranitidine \t۲۵ mg/ml (۲ ml)",
  "Tablets:\t۱۲.۵ mg",
  "Clavulanic Acid \t۵۷mg/۵ ml (as Potassium Salt)",
  "Double Scored Tablets:\t۵۰۰ mg",
  "Potassium Chloride\t۴۶.۶ mg/Sachet",
  "Infusion: Dextrose ۵% NaCl ۰.۴۵% (۵۰۰,۱۰۰۰ml)",
  "Tablets: \t۱۰ mg",
  "For Continuous I.V.Infusion:\t۴%(۵۰ml)",
  "Vitamin B۱۲ \t۱۵ mcg and",
  "Injection:\t۲۵ mg/۱۰ ml",
  "Yellow Soft Paraffin\t۸۰ g and",
  "Capsules: ۱۵۰ mg",
  "Mouth Wash:\t۰.۲% (۲۵۰ ml)",
  "Topical Cream: Betamethasone \t۰.۱%",
  "Folic Acid\t۱ mg",
  "Effervescent Tablets:",
  "Effervescent Tablets: (Phosphate , Sodium)",
  "Amoxicillin\t۲۵۰ mg (as Trihydrate) and",
  "Tablets: ۴۵۰ mg",
  "Topical Solution:\t۵%(۱۵۰ ml, ۱۰۰۰ ml, ۴ lit)",
  "For Ophthalmic Solution:\t۵۰۰۰۰۰ Units/Vial",
  "◇ Coated Tablets:",
  "Injection: \tMethotrexate* \t۱۰۰ mg/ml (as Sodium Salt)",
  "Tablets: ۴۰۰ mg",
  "Nasal Spray (Salmon):\t۲۰۰ IU/ Dose",
  "Syrup:\t Paromomycin \t۱۲۵ mg/۵ ml",
  "Tablets: ۵۰۰ mg",
  "For Injection:\t۵۰ mg/Vial (as Sodium)",
  "Tablets: ۱۵۰ mg",
  "Lotion:\t۵%",
  "Film Coated Tablets:\t۶۰۰ mg",
  "For Injection:\t۵ mg/Vial",
  "Wool Fat\t۱۰ g and",
  "For Injection: Capreomycin \t۱ g/Vial",
  "Scored Film Coated Tablets:\t۲۵۰ mg",
  "Scored Tablets:\t۱ g",
  "Injection (Single-use vial): ۷۵ IU/vial",
  "For Injection: ۱۰۰ mg/Vial",
  "Tablets:\t۱۰۰ mg",
  "Injection Solution: \t۲۵۰ mcg/ml (۲۵ml, ۵۰ml)",
  "Sterile Eye Drops:\t۰.۳۰% (as HCl)",
  "For Injection:\t۱ g/Vial",
  "Trimethoprim\t۴۰ mg/۵ ml",
  "Sustained Release Tablets:\t۵۰۰ mg",
  "Caffeine\t۱۰۰ mg and",
  "Co- Amoxiclav ۱۵۶",
  "Cl - \t۱۲۰ mmol / lit",
  "Coated Tablets: Trifluoprazine \t۱۰ mg",
  "K+\t۴ mEq/Lit and",
  "Sulbactam \t۱ g/Vial (as Sodium)]",
  "For Injection: Nafcillin\t۵۰۰ mg/Vial (as Sodium Salt)",
  "Ophthalmic solution: ۰.۰۱%",
  "Syrup:",
  "I.V.Infusion:\t۵۰ mg/۱۰۰ ml",
  "For Suspension:\t۲۰۰ mg/۵ ml (as Dihydrate) (۳۰ ml)",
  "Capsules: ۱۴۰ mg",
  "Isoniazid\t۵۰ mg and",
  "Delayed Release Tablets: \t۲۰ mg (as Sodium Sesquihydrate)",
  "Extended Release Capsules: \t۰.۴ mg",
  "Injection:\t۶۰ mg/۲ml",
  "Tablets:  ۹۰ mg",
  "Carbidopa\t۲۵ mg",
  "Sterile Otic Drops (Solution or Suspension):",
  "Infusion: (۵۰۰,۱۰۰۰ml)",
  "Topical Cream:\t۰.۲۵%",
  "I.V.Injection:\t۱%(۵ml)",
  "Scored Tablets:\t۵ mg",
  "Elixir:\t\t۰.۰۵ mg/ml (۶۰ ml)",
  "Coated Tablets:\t۴ mg",
  "Sustained Release Tablets:\t۲۰۰ mg",
  "Sodium Hydrogen Carbonate \t۱۷۸.۵ mg and",
  "Spray:\t \t۲۵/۵۰",
  "Scored Tablets: \t۴۰۰ mg",
  "Sterile Eye Drops:\t۵%",
  "Patch: Each patch contains ۳۴.۳ mg/۵۲ cm۲ (delivers ۳.۱ mg/۲۴ hr)",
  "Amoxicillin\t۱۲۵ mg/Sachet (as Trihydrate) and",
  "Tablets:\t۱۲۵ mg",
  "Glutathione Disulfide\t۴.۶ mg",
  "Oral Solution: ۵۰ mg/ml (۲۵۰ mg/۵ ml)",
  "Spray:\t\t۱۲۵ mcg/Dose",
  "Powder for Oral Suspension:  ۲۴۰۰ mg/packet",
  "Tablets:\t۴۵ mg (as Gluconate)",
  "Tablets: ۳۷۵ mg",
  "Enteric Coated Tablets:\t۳۰۰ mg",
  "Infusion Solution:\t۳۵۰ mg I/ml (۲۰, ۵۰, ۱۰۰, ۲۰۰ ml)",
  "For Injection: ۱۰ mg/vial",
  "Capsules: ۷۵ mg",
  "Injection:\t۲۰ mg/ml (۲.۵ ml)",
  "Injection:\t۱۰ mg/ml",
  "For Injection:\t۲۵ mg/Vial",
  "Sterile Eye Drops:\t۰.۱%",
  "Coated Tablets:\t۵۰۰ mg (as ۳H۲o)",
  "Sterile Eye Drops (Suspension):\t۵%",
  "For Injection: Cyclophosphamide \t۵۰۰ mg+ Diluent",
  "Injection:\t۲۰۰ mcg/ml",
  "Injection:\t۱ g/۵ ml",
  "◇ Vaginal Tablets: \t۵۰۰ mg",
  "For Injection: \t۴۰ mg/Vial (as Sodium)",
  "For Injection:\t۱ g",
  "Suppositories:\t۳۲۵ mg",
  "◇ Oral Solution:\t۴۰ mg/ml",
  "Nicotinamide\t۳.۷۵ mg and",
  "Injection Solution: ۳۰ mg/mL",
  "Casules:\t\t۱۰۰ mg",
  "Extended-Release Tablets: ۱.۵ mg",
  "For Injection:\t۰.۲۵ mg",
  "Tablets:  ۱۰۰ mg",
  "Injection Solution:\t۲۰ mg / ۰.۵ ml (۰.۵ و ۱و ۱۰ ml)",
  "هر ۱mcg ویتامین D ، معادل ۴۰ U است.",
  "For Infusion:\t۱ mg/ ml (۱ ml)",
  "Scored Tablets:\t۲۵۰ mg (as HCl)",
  "Vaginal Tablets:\t۳ mg",
  "Injection:\t۱۰۰ mg/ml (Eq to Pentavalent Antimony)",
  "Ca\t۱۰۰ mg and",
  "Sustained Release:\t۴۰۰ mg",
  "Capsules: Procarbazine \t۵۰ mg",
  "Tablets: ۰.۵ mg",
  "◇ Tablets:\t۰.۷۵ mg",
  "Amoxicillin\t۴۰۰ mg/۵ ml (as Trihydrate) and",
  "Cod Liver Oil\t۵۰% and",
  "Na۲HPO۴ \t۰.۴۳۳ mg",
  "Capsules: \t۲۵ mg",
  "For Injection:\t۱,۰۰۰,۰۰۰ U/Vial",
  "Zn\t۰.۵ mg and",
  "Infusion: ۲۰%* (Eq.to ۲۰g Dextrose/۱۰۰ml) (۵۰,۵۰۰,۱۰۰۰ml)",
  "Nasal Spray\t۱۵۰ mcg/Dose",
  "Infusion: Dextrose ۵% NaCl ۰.۹% (۲۵۰,۵۰۰,۱۰۰۰ml)",
  "Injection:\t۲۵۰ mg/۱۰ ml",
  "Capsules or Tablets:\t۵۰۰۰۰ U.",
  "For Oral Suspension:",
  "Epinephrine (Bitartrate)\t۱۲.۵ mcg/ml",
  "Tablets: ۳۰۰ mg",
  "Film Coated Tablets:\t۵۰۰ mg",
  "Tablets: ۰.۵ mg",
  "Tablets: Azathioprine\t ۵۰ mg",
  "Dextrose\t۷.۵%",
  "◇ Sustained Release Tablets:\t۸۰ mg",
  "Sterile Eye Drops",
  "Injection: Haloperidol\t۵ mg / ml (as Lactate)",
  "Clidinium Bromide\t۲.۵ mg and",
  "Oral Solution: \t۱۰ mg/ml",
  "Suspension:\t۱ mg/ml",
  "Film Coated Tablets:\t۴۰۰ mg",
  "For Infusion:\t۱۰ mg/۱۰ ml",
  "Lotion Shampoo:\t۲.۵% (۲.۵ g/۱۰۰ ml)",
  "For Infusion:\t۷.۵%",
  "Syrup:\t Total Alkaloid\t۰.۱۴% (۳۰ ml)",
  "For Injection:\t۲۰ mg/Vial",
  "Inhaler:\t۱۰ mg/Container (۴۲ mcg/Inhalation)",
  "Tablets:\t۵ mg",
  "Injection:\t۲۴۰ mg I/ml (۲۰, ۵۰ ml)",
  "Tablets:\t \t۲۰ mg",
  "Tablets:\t۱۲۰ mg",
  "◇ Oral Drops:\t۵۵۰ mcg/۰.۱۵ ml (۶۰ ml)",
  "Coated Tablets:\t۵۰۰ mg (as Carbonate)",
  "Injection:\t۱۰۰۰ UAH/ml (۱۰ ml)",
  "Inhaler:\t۲۰ mcg/Dose",
  "Pellets:\t۱۳-۱۶ mg",
  "Powder for Oral Use: ۱۰ mg Sodium Picosulfate/۳.۵ g Manesium oxide/۱۲ g Anhydrous Citric Acid per Packet",
  "◇ Capsules:\t۱۰ mg",
  "Coated Tablets:\t۱۰۰ mg",
  "Scored Tablets: Bromocriptine\t۲.۵ mg",
  "Injection:\t۵۰ mg/۵ ml",
  "Tablets:\tMethotrexate \t۲.۵ mg or",
  "BULK",
  "Topical Cream: \t۲%",
  "Nasal spray: ۶۶۵ mcg/Puff (۰.۶%)",
  "Tablets or Capsules:  ۷۵ mg",
  "◇ For Suspension:\t۱۲۵ mg/۵ml (as Axetil)",
  "Oral Drops:\t۱۲۵ mg (۲۵ mg Iron)/ml",
  "Solution for Subcutaneous Injection: ۲۰ mg/mL",
  "Injection:\t۱۰ mg/ml (۵ ml)",
  "Topical Ointment: Betamethasone \t۰.۱%",
  "مقدار ۱.۱g نفسیلین سدیم، تقریباً معادل ۱g نفسیلین است.",
  "Injection:\t۲۰%",
  "Titanium Oxide\t۳.۶% and",
  "Tablets or Scored Tablets:\t۲۵۰ mg",
  "Syrup:\t\t۵ mg/۵ ml (as HCl) (۶۰ ml)",
  "Vitamin D\t۸۵ I.U./g",
  "Suspension:\t۸%(۱۲۰,۲۴۰ ml)",
  "Powder for Injection: \t۵ mg/ Blister Pack",
  "CaHPO۴ ۲H۲O\t۱۲۹ mg and",
  "Extended-Release Tablets: ۰.۷۵ mg",
  "Patch:\t۵۰ mcg/h",
  "For Injection:\t۷۵ I.U. FSH",
  "Tablets: ۲۵۰ mg",
  "For I.V.Infusion: Dobutamine \t۱۲.۵ mg/ml (۲۰ ml)",
  "Copper\t۰.۲۵ mg and",
  "Scored Film Coated Tablets:\t۸۰ mg",
  "Capsules: ۵ mg",
  "Injection: Amikacin \t۱۰۰mg/۲ml",
  "For Injection:\t۱۰۰ mg",
  "Allantion\t۲%",
  "Topical Gel:\t۲%",
  "Syrurp:\t۲۰۰ mg/۵ ml (۲۴۰ ml)",
  "Cu\t۱ mg and",
  "CaCl۲ , ۲H۲O\t۰.۲۱ g / ۱۰۰۰ ml",
  "در هر میلی‌لیتر از محلول II :",
  "For Injection:\t۲۵۰۰۰۰ I.U./Vial",
  "Nasal Drops:\t۰.۶۵%",
  "Film Coated Tablets: \t۱۲ mg",
  "Mouth Wash:\t۰.۰۵% (۲۰۰,۲۴۰ ml)",
  "◇ Injection:\t۱۰۰ mg/ ml (۱۰ml)",
  "CaCl۲ Dihydrate\t۳.۸۵ mg",
  "Injection:\t۱۰,۰۰۰ I.U./ml",
  "Nasal Drops:\t۰.۲۵%",
  "For Injection:\t۵۰ mcg/Vial",
  "Coated Tablets:\t۷۵ mg",
  "Vitamin D\t۱۲۵ I.U. and",
  "Tablets:  ۶۰ mg",
  "Calcium (as Carbonate)\t۱۲۵ mg and",
  "Injection: ۰.۴ mg/ml",
  "Iodine (as Potassium)\t۱۵۰ mcg and",
  "Betamethasone \t۳ mg/ml (as Disodium Phosphate)",
  "Tablets:\t \t۵ mg",
  "Extended-Release Tablets: ۰.۳۷۵ mg",
  "Solution for injection: ۵۰۰ mg/۱۰۰mL",
  "Injection:\t۰.۵ mg /ml (۱ ml) (as Sulfate)",
  "Suspension:\t۵۰۰ mg/۵ ml",
  "Solution for injection: ۲۰ mg/ml (۳۰۰ mg/۱۵ mL)",
  "MgCl۲ Hexahydrate\t۵ mg",
  "Tablets\t: \t۴۰ mg",
  "Suppositories:\t۱۰ mg",
  "Injection:\t۷۶% (۲۰ml, ۱۰۰ml)",
  "Sustained Release Capsules:\t۱۲۰ mg",
  "Coated Tablets: Fluphenaine ۲HCL\t۱ mg",
  "Injection: Gentamicin\t۲۰ mg / ۲ ml (as Sulfate)",
  "For Injection: \tMethotrexate* \t۱ g (as Sodium Salt)",
  "Powder for Injection: ۳۸۰ mg/vial",
  "Capsules:\t۵ mg",
  "Spray:",
  "Sterile Eye Drops:\t۰.۵% (۱۰ ml)",
  "Chewable Tablets:\t۴۰ mg",
  "Clavulanic Acid \t۶۲.۵ mg/Sachet (as Potassium Salt)",
  "Liquid Paraffin\tQS to ۱۰۰ g",
  "Injection:\t۱۰ ml",
  "Tablets:\t۰.۰۳ mg",
  "Scored Tablets:\t۲۰ mg",
  "Injection: Haloperidol\t۵۰ mg / ml (as Decanoate)",
  "Enteric Coated Tablets:\t۸۰ mg",
  "Vitamin B۲\t۱.۷ mg and",
  "Scored Coated Tablets:\t۵۰ mg",
  "Mg\t۵ mg and",
  "Coated Tablets:\t۲ mg",
  "Primethamine\t۲۵ mg",
  "Chlorhexidine Gluconate\t۱.۵% (۲۵۰ ml,۴ lit.)",
  "Desoxyribonuclease\t۲۰۰۰۰ U/۳۰ g",
  "Injection:\t۴ mcg/ml",
  "Phenylephrine HCl\t۰.۱۲ % W/V and",
  "Scored Film Coated Tablets:\t۲۰ mg",
  "Capsules or Tablets: Quinine \t۲۰۰ mg (as Sulfate)",
  "Delayed Release Capsules: ۲۰ mg",
  "For Injection: \tMethotrexate* \t۵ mg (as Sodium Salt)",
  "Topical Gel:\t۱۰%",
  "Powder for Injection:\t۱g",
  "Chewable Tablets:",
  "Sterile Eye Drops:\t۵۰ mg/ml",
  "Scored Tablets: \t۱۲۵ mg",
  "I.V.Infusion:\t۱۰۰ mg/۵ ml",
  "Injection:\t۱%",
  "Capsules: \t۱۶۰ mg",
  "Injection: \t۸۰ mg/ Phospholipids /ml",
  "Scored Tablets: Prazosin \t۵ mg",
  "For Injection: \t۱۵۰ mg/Vial",
  "Injection Solution: ۱mg/ml",
  "Plaster: Estradiol S.R. \t۸ mg/۲۰ cm۲ (۱۰۰ mcg/۲۴ h)",
  "Hydrocortisone \t۱۰ mg/۱ ml",
  "For Injection: \t۱۰۰ mg/Vial (۲۰ ml)",
  "Injection:  ۷۵۰mg/۱۵ml (۵۰mg Ferric/ml)",
  "Capsules:\t۲۰ mg",
  "For Ophthalmic Ampules: \t۱%",
  "Tablets: \t۰.۵ mg",
  "Epinephrine\t۱/۲۰۰۰۰۰",
  "Injection:\t۵۰۰ mg/۵ ml",
  "injection:\t۱۰ mg/ml (۲ ml, ۴ ml)",
  "Injection: Chloroquine\t۲۰۰ mg/۵ ml (as Phosphate)",
  "Injection:\t۵ mg/۵ ml",
  "FSH\t۷۵ IU and",
  "◇ Powder for Syrup:\t۱۰ g/Sachet",
  " Suspension: \t۲۵ mg Phospholipids/ ml (۸ml)",
  "Phenylephrine HCl\t۱.۲۵ mg/۵ ml and",
  "Scored Tablets:\t۸۰ mg",
  "For Injection:\t۶۰۰۰۰۰ Units/Vial",
  "Nasal Spray:\t۱۰ mcg/dose",
  "For Injection:\t۵۰ mg",
  "Amoxicillin\t۱۲۵ mg/۵ ml (as Trihydrate) and",
  "Film Coated Double Scored Tablets:\t۴۰۰ mg",
  "Dextromethorphan HBr\t۱۵ mg/۵ ml and",
  "For Injection:\t۱۰۰ mcg",
  "Suspension:\t۲۵۰ mg/۵ ml",
  "Topical Cream:",
  "Neomycin Sulfate\t۵ mg/۱ ml and",
  "Capsules:\t۱۰ mg",
  "NaHCO۳\t۲.۱۹ mg",
  "Inhaler:\t۴۰ mcg/Dose",
  "For Injection:\t۳ g",
  "Film Coated Tablets:\t۱۵۰ mg",
  "For Injection:\t۴۰۰۰۰۰ Units/Vial",
  "For Injection: Cefepime \t۱ g/Vial (as HCl)",
  "Capsules: ۳۰ mg",
  "Syrup:\t\t۲۰ mg/۵ ml",
  "Tablets:  ۲.۵ mg",
  "Powder for Oral Suspension:\t۴ g/Sachet",
  "Film Coated Tablets:\t۳۰۰ mg",
  "Tablets: Quinine \t۲۵۰ mg (as HCl)",
  "Ophthalmic Ointment: \t۳%",
  "Fentanyl (as Citrate)\t۰.۵mg/۱۰ ml",
  "Injection Solution: \t۱%",
  "Tablets: ۱۰۰ mg",
  "۱mcg از پنی‌سیلین تقریباً معادل ۱.۶Unit پنی‌سیلین است.",
  "Tablets: \t۵ mg",
  "Elemental Iron\t۲.۵ mg and",
  "chewable Tablets:\t۵ mg",
  "Injection:\t۴۰ U/ml",
  "Injection: Gentamicin\t۸۰ mg / ۲ ml (as Sulfate)",
  "Oral Solution: Haloperidol\t۲ mg / ml (as Lactate)",
  "Tablets: \t\t۱ mg",
  "Lotion: Betamethasone\t۰.۱% (W/ W or W/ V)",
  "Injection:\t۲۰ mg/۲ ml",
  "Vitamin A\t۵۰۰۰ I.U.and",
  "Padimate O\t۳.۲% W/W",
  "Tablets:\t ۲۰۰ mg",
  "Tablets:\t۰.۲۵ mg",
  "For Injection: Leucovorin Ca \t۳۰ mg/Vial or",
  "Capsules: Clindamycin \t۱۵۰ mg (as HCl)",
  "Sustained Release Enteric Coated Tablets:\t۵۰۰ mg",
  "Enema:\t۳ g/۱۰۰ ml",
  "For Injection:\t۰.۱۵ mg",
  "Spray",
  "Scored Tablets:\t۳۰۰ mg",
  "Lotion:\t\t۸% (۶۰ ml)",
  "Double Scored Tablets:\t۱۰۰ mg",
  "Coated Tablets:\t۵۰۰ mg",
  "Topical cream:\t۴%",
  "For Injection:\t۵,۰۰۰,۰۰۰ U/Vial",
  "Injection:\t۱۰ mg/۱۰ ml",
  "Sustained Release Tablets:\t۶۰ mg",
  "Chewable Coated Tablets:\t۱۰۰ I.U.",
  "Insulin Aspart Crystallised With Protamine \t۷۰%)",
  "for Injection",
  "◇ Soap:\t\t۱۰% (W/W)",
  "Injection Solution:  ۱۲۰ mg/۱.۷ ml",
  "Soap:\t\t۱% (۷۵ g)",
  "Suppositories:\t۱۰۰ mg",
  "Nasal Spray (Salmon):\t۱۰۰ IU/ Dose",
  "Oral Paste: Triamcinolone\t۰.۱%",
  "Injection: \t۱ mg/۲ ml",
  "Lidocaine\t۵% and",
  "Injection: Mitoxantrone \t۲ mg/ml (as HCl)",
  "For Injection:\t۲۰۰ mg/Vial",
  "Chewable Tablets:\t۳۰۰ mg",
  "Injection: Leucovorin Ca \t۲۵ mg/۵ ml",
  "Ethinyl Estradiol\t۴۰ mcg",
  "Film Coated Tablets:\t۷۵ mg",
  "Strip:\t\t۱ mg/strip",
  "Capsules:\t۵۰۰ mg",
  "Potassium not less than\t۷.۵ mg and",
  "Capsules: ۲۵ mg",
  "◇ For Suspension:\t۱۰۰ mg/۵ml (۵۰ ml)",
  "Film Coated Tablets: ۷ mg",
  "Chewable Coated Tablets:\t۴۰۰ I.U.",
  "Ophthalmic Suspension:\t۱%",
  "For Suspension:\t۱۲۵ mg/۵ ml",
  "I.V. Injection:\t۱۲.۵ g/۵۰ ml",
  "Film Coated Tablets or Capsules: Nortriptyline \t۲۵ mg",
  "◇ For Suspension:\t۲۵۰ mg/۵ml (as Axetil)",
  "Vitamin E\t۳۰ I.U. and",
  "Prilocaine HCl\t۳% (۳۰ mg/ml) and",
  "Sterile Ophthalmic Solution: Boric Acid \t۱۶۱۰ mg/۱۰۰ ml",
  "BULk",
  "Tablets:\t۱۵ mg (as Phosphate ۲۶.۳ mg)",
  "For Inhalation:\t۲۵۰ ml/Bottle",
  "Lyophilized Powder for IV Infusion: ۱۰۰ mg/vial",
  "Capsules: Phenytoin Sodium \t۵۰ mg",
  "Injection:\t۵۰% (۱۰ ml)",
  "For Injection:\t۱ g/Vial+Diluent",
  "Manganese\t۰.۲۵ mg and",
  "Oral Solution:\t۰.۲۵ mg/ml",
  "Ammonium Chloride\t۱۲۵ mg/۵ ml",
  "Patch:\t۲۵ mcg/h",
  "For Injection: \t۱۰۰ I.U./ml (۳ ml)",
  "Inhaler:\t۲۵ mcg / Dose",
  "Injection: Betamethazone \t۴mg/ml (as Disodium Phosphate)",
  "◇ Oral Drops:\t۱.۱ mg/ml (۵۰ ml)",
  "Tablets: ۲۰۰ mg",
  "Fluticason Propionate \t۱۲۵ mcg",
  "Oral Topical Solution:\t۰.۱۵ %",
  "(Levodopa ۱۰۰mg and Benserazide HCl ۲۵mg)",
  "Sulfamethoxazole\t۲۰۰ mg/۵ ml and",
  "Topical Ointment: \t۵۰ mcg/g (۳۰ g)",
  "For Injection:\t۱۰۰ mcg (۳ million I.U.)/Vial",
  "Tablets: Metoclopramide \t۱۰ mg",
  "Erythromycin\t۳% and",
  "Tablets:\t۰.۲ mg",
  "Na Citrate, ۲H۲O\t۰.۱۷%",
  "Soap:\t\t۱۰% (۱۰۰ g)",
  "Powder for Inhalation:\t۴۰۰ mcg/Inhalation",
  "Topical Cream:\t۲۰%",
  "Injection:\t۴%",
  "Vitamin B۱\t۱.۵ mg and",
  "Injection:\t۰.۵ mg/۵ ml",
  "Injection Solution:\t۱۰%",
  "For Injection:\t۱۰ mg/Vial",
  "Tablets\t: \t۵۰۰ mg",
  "Sterile Ophthalmic Solution II:\t۲۰ ml",
  "Carbidopa\t۱۰ mg",
  "Scored Tablets:\t ۵۰ mg",
  "Injection:\t۰.۵ mg/۲ ml",
  "For Injection:\t۷۵۰۰۰ I.U./Vial",
  "Copper Sulfate\t۱g and",
  "Sterile Eye Drops:\t۲%",
  "Infusion :\t۰.۹% (۵, ۵۰۰, ۱۰۰۰ ml)",
  "Sucrose\t۴ g/۱۵ g Sachet",
  "Gelatin Succinylate\t۳۰ g and",
  "Tablets: ۱۲۰ mg",
  "Sustained Release Tablets:\t۴۰ mg",
  "Injection:\t۶ mg/ml",
  "K۲PO۴\t۲۳۶ mg/ml",
  "Injection:\t۲ mg/ml (۲ ml, ۴ ml)",
  "For Injection:\tCefazolin ۱g/Vial",
  "Tablets: ۴۰ mg",
  "Capsules or Tablets:",
  "Topical Solution:\t۲%",
  "For Injection: Cefepime \t۲ g/Vial (as HCl)",
  "[Ampicillin\t۱ g/Vial (as Sodium) and",
  "Tablets:\t۲ mg (as Sulfate)",
  "Injection: \t۲۵۰ mg/ml",
  "For Injection:\t۲۰۰۰ U/Vial",
  "Capsules: Phenytoin Sodium \t۱۰۰ mg",
  "Scored Coated Tablets:\t۵۰ mg (as Monohydrate)",
  "Scored Tablets:\t۰.۵ mg",
  "◇ Granules:\t۱ g/Sachet",
  "Extended-release capsules:  ۷۵ mg",
  "Tablets: \t۶۰ mg",
  "Coated Tablets:\t۱۵ mg",
  " Sterile Eye Drop: \t۲%",
  "Cream: ۰.۰۵%",
  "Capsules or Scored Coated Tablets:\t۵۰۰ mg",
  "For Injection:",
  "Ferrous\t۶۰ mg (as Fumarate) and",
  "For Injection: Chloramphenicol \t۱g/Vial (as Sodium Succinate)",
  "For Injection:\t۱۲۰ mcg/Vial",
  "Scored Tablets:\t۲۵ mg",
  "Topical Cream: Hydrocortisone\t۱%",
  "Tablets: ۱۵۰ mg",
  "For Infusion:\t۱۰ mg/۵ ml",
  "Co- Amoxiclav ۳۱۲",
  "Solution for injection: ۱۰ mg/ml (۶ mg/۰.۶ ml)",
  "Capsules:\t۱.۵ mg",
  "Ca++\t۳ mEq/Lit and",
  "(Levodopa ۲۰۰mg and Benserazide HCl ۵۰mg)",
  "Sustained Release Tablets:\t۱۶۰ mg",
  "Tablets: ۳۰ mg",
  "Spray:\t \t۲۵/۲۵۰",
  "◇ Film Coated Tablets:\t۱۵۰ mg",
  "Tablets: ۱۰ mg (As Benzoate or Hydrogen Tartrate)",
  "Tablets:",
  "Injection: Nandrolone Decanoate\t۲۵ mg/۱ ml",
  "Tablets: ۵۰ mg",
  "Injection:\t۵۰ mg/۱۰ ml",
  "Powder for Solution: ۳۰ mg/۵ ml",
  "Injection:\t۵۰ mg/ml (۵ ml)",
  "For Oral Suspension: \t۴۰۰۰۰۰ I.U/۵ ml (as Benzathine)",
  "Nicotinamide\t۲۰ mg and",
  "Nasal Drops:\t۰.۰۵%",
  "Sterile Eye Drops:\t۱% (۱۰ ml)",
  "Capsules:\t۴.۵ mg",
  "Topical Cream:\t۱۰ %",
  "Injection: Leucovorin Ca \t۳ mg/ml",
  "Topical Cream:\t\t۸%",
  "Nicotinamide\t۵۰ mg and",
  "Injection:\t۳۷۰ mgI/ml (۲۰ml, ۵۰ml, ۱۰۰ml)",
  "Salmeterol\t۲۵ mcg(as Xinafoate) and",
  "Sustained Release Coated Tablets:",
  "Injection:\t۳ mg/ml (۲ ml)",
  "Injection:\t۳ million IU/ml",
  "Injection:\t۲۵ mg/۵ ml",
  "Suspension:\t۴۰۰mg/۱۰ml",
  "Menthol\t۱ mg/۵ ml",
  "Topical Cream: \t۲۰%",
  "Amoxicillin\t۲۰۰ mg/۵ ml (as Trihydrate) and",
  "Louzangers:",
  "Diatrizoate Sodium\t۱۰%)",
  "Scored Tablets:\t۴ mg",
  "Capsules:\t۵۰۰۰۰ U",
  "For Injection:\t۵ mg",
  "(Diatrizoate Meglumine\t۵۲.۱% and",
  "For Injection:\t۱۵۰ mcg/Vial",
  "For Suspension:\t۱۰۰ mg/۵ml (۱۰۰ ml)",
  "For Inhalation",
  "Chewable Coated Tablets:\t۲۰۰ I.U.",
  "Phenyl Propanolamine HCl\t۵ mg/۵ ml",
  "Topical Gel:\t۰.۵% W/W",
  "Chewable Tablets:\t۵۰۰ mg",
  "Clotrimazole \t۱% and",
  "Injection: Glucagon\t۱ mg / ml (as HCI)",
  "Scored Tablets:\t۱۰۰ mg",
  "Artemether \t۲۰ mg and",
  "Tablets: ۲۰ mg",
  "Tablets: ۶۰۰ mg",
  "Acetaminophen\t۳۲۵ mg and",
  "Film Coated Tablets:\t۱۰۰ mg",
  "For Infusion:\t۲۰ mg/ml (۲, ۵ ml)",
  "Spray:\t\t۵۰ mcg/Dose",
  "Injections: ۴۰mg/۰.۸ml",
  "Injection:\t۵۰ mg/۲ ml",
  "Syrup:\t Levamisole \t۴۰ mg/۵ ml (as HCl)",
  "Film Coated Tablets:",
  "Injection: \tMethotrexate* \t۲.۵ mg/ml (as Sodium Salt)",
  "Tablets or Capsules:\t۵۰ mg",
  "Calcium Caseinate\t۱۰.۵ g and",
  "Film Coated Tablets:\tEq. To ۵۰ mg Fe++",
  "Syrup:\t\t۱ mg/ml (۶۰ ml)",
  "Capsules:\t۲۵۰ mg (as Dihydrate)",
  "Injection Solution:  ۶۰ mg/ml",
  "For Injection:\t۲ g",
  "مقدار ۵۰۰mg نئومایسین سولفات، تقریباً معادل ۳۵۰mg نئومایسین است.",
  "◇ Injection: Phenobarbital \t۱۰۰ mg/ml",
  "For Suspension:\t۲۰۰ mg/۵ ml (۱۰۰ ml)",
  "Lysine\t۰.۶۵ g and",
  "Powder For Injection: ۵۰ mg/vial",
  "Coated Tablets:\t۴۰ mg",
  "Granules:\t۵ g/Sachet",
  "Injection Solution:\t۱۰ mg/۱ ml",
  "Tablets: ۵۰ mg",
  "Sulfamethoxazole\t۴۰۰ mg/۵ ml and",
  "◇ Film Coated Tablets:\t۵۰۰ mg(as Axetil)",
  "Capsules:\t۵۰ mg",
  "For Continuous I.V.Infusion:\t۱%(۵۰ml)",
  "Vitamin A\t۸۵۰ I.U./g and",
  "Injection Solution: Epinephrine\t۱ mg/ml",
  "For Injection: \t۱۰.۴ Units/Vial",
  "Topical Solution:\t۱۰% (۶۰,۲۵۰,۱۰۰۰,۳۸۰۰ ml)",
  "Sustained Release Tablets:\t۸ mg",
  "liquid-Filled Capsules: ۲۵ mg",
  "Topical Solution:\t۱% (۲۰ mL)",
  "Oral Solution:\t۱g/۱۰ml",
  "Aerosol inhalation: ۸۰ mcg/Puff",
  "Cartrige:\t۳% (۱.۸ml)",
  "Topical Cream:\t۱%",
  "For Oral Solution:",
  "Injection:\t۲۰ Pressor U/ml",
  "Aerosol inhalation: ۱۶۰ mcg/Puff",
  "Sterile Eye Drops:\t۱۴ mg/ml (۱۰ ml)",
  "Mequinol\t۱۰% and",
  "For Injection:\t۱ mg/ml",
  "Vaginal Cream:\t۲%",
  "For Injection:\tCefazolin ۵۰۰ mg/Vial",
  "Topical Ointment: Hydrocortisone\t۱%",
  "Levodopa\t۲۵۰ mg and",
  "Injection:\t۱۰۰ I.U./ml (۳ ml)",
  "Scored Tablets:\t۶۰ mg",
  "Film Coated Tablets:\t۲۵ mg",
  "Injection: Citicoline \t۲۵۰ mg/۲ ml",
  "Injection:\t۳۰۰ mg/۳ ml",
  "Topical Solution:\t۴% (as HCl)",
  "Chewable Tablets:\t۲۰۰ mg",
  "Coated Tablets:",
  "Plaster: Estradiol S.R. \t۲ mg/۵ cm۲ (۲۵ mcg/۲۴ h)",
  "For Injection:\t۱۰۰۰ U(Concentrated)",
  "For Oral suspension:\t۲۵۰ mg/Sachet",
  "Injection: Cimetidine \t۲۰۰ mg/۲ ml (as HCl)",
  "Calcium\t۵۰۰ mg(as Carbonate) and",
  "Injection Solution:\t۵۰ mg/۲ ml",
  "Capsules: \t۱۲۵ mg",
  "Lactate\t۲۸ mEq/Lit",
  "Infusion: Dextrose ۳.۳۳% NaCl ۰.۳% (۵۰۰,۱۰۰۰ml)",
  "Capsules:  ۵ mg",
  "Vitamin B۱\t۲۰ mg and",
  "◇ For Injection:\t۷۵۰ mg (as Sodium Salt)",
  "۵: Levonorgestrel\t۰.۰۷۵ mg and",
  "For Injection: \t۵۰ mg/Vial",
  "Antazoline Phosphate\t۰.۵%",
  "Injections: ۳۰ mg/ml",
  "Tablets:  ۲۵۰ mg",
  "Scored Coated Tablets:\t۷۵ mg",
  "Injection:\t۱.۵ g/۵ ml",
  "Acetyl Salicylic Acid\t۵۰۰ mg and",
  "Effervescent Tablets:\t۱۰۰۰ mg",
  " For Injection:\t۱ g/Vial (as Trihydrate)",
  "Caffeine\t۳۲.۵ mg",
  "Fibrinolysin\t۳۰ U/۳۰ g and",
  "◇ Syrup:\t\t۵ mg/۵ ml (۶۰ ml)",
  "مقدار ۲۵۰mg کینیدین بی‌سولفات، تقریباً معادل ۲۰۰mg کینیدین سولفات است.",
  "For Injection:\t۵۰۰۰ Units",
  "Chlormadinone Acetate \t۲ mg and",
  "For Injection: Bleomycin \t۱۵ U",
  "For Oral Suspension:\t۱ g/Sachet",
  "Delayed Release Capsules: ۶۰ mg",
  "Sterile Eye Drops:\t۱%",
  "Tablets: \t۱۰۰ mg",
  "Vitamin D\t۱۰۰۰ I.U.and",
  "Choline Bitartrate N.F.\t۲۵ mg and",
  "Injection: Gentamicin\t۴۰ mg / ۱ ml (as Sulfate)",
  "Topical Cream: Mafenide \t۸۵ mg/g",
  "For Inhalation:\t۱۰۰ ml",
  "Oral Solution:\t۱۰ mg/ml",
  "Tablets:\t۱۰ mg",
  "Vitamin C\t۱۲.۵ mg and",
  "Powder:\t۲۰ mEq/Sachet",
  "Oral Suspension:\t۱۰۰ mg/۵ ml",
  "Mouth Wash:\t۱%",
  "For Injection:\t۹۰ mg",
  "Salbutamol (as Sulfate)\t۱۰۰ mcg/Dose",
  "Scored Tablets: \t۶۲.۵ mg",
  "Estradiol Cypionate\t۵ mg/۰.۵ ml",
  "Capsules:\t۱۴۰ mg",
  "Vaginal Cream:\t۰.۰۱%",
  "Injection:\t۱۰۰ IU/ ml",
  "Biotin\t۰.۲۵ mg and",
  "Scored Tablets:\t ۰.۵ mg",
  "capsules: ۰.۵ mg",
  "Ophthalmic Ointment:\t۱%",
  "For Infusion Solution:\t۱۰۰ mEq/۵۰ ml",
  "Vitamin B۱۲\t۵ mcg and",
  "Magnesium (as Magnesium Oxide)\t۱۰۰ mg",
  "Vaginal Tablets:\t۵۰۰ mg",
  "Atovaquone \t۶۲.۵ mg and",
  "Sustained Release Capsules:\t۲۰۰ mg",
  "Na+\t۱۴۷ mEq/Lit and",
  "Nasal spray: ۵۰ mcg/Actuation",
  "Capsules: ۱۰ mg",
  "Injection: ۱۰۰ mcg/mL",
  "Sterile Eye Drops (Suspension):\t۱%",
  "Topical Aerosol (Spray):\t۱۰ mg/dose (۵۰ mg)",
  "Scored Film Coated Tablets:\t۱۰۰ mg",
  "Injection:\t۴۰ mg/ml (۲ ml)",
  "Disinfectant Solution:\t۲%",
  "Co- Amoxiclav ۲۲۸",
  "Rectal Tube:\t۵ mg",
  "Vitamin C\t۶۰ mg and",
  "Capsules: Disopyramide \t۱۰۰ mg",
  "For Injection:\t۴ I.U./Vial",
  "Phosphorous\t۳۰.۵ mg and",
  "Trimethoprim\t۲۰ mg",
  "Suppositories:\t۵ mg",
  "Capsules: ۲۵۰ mg",
  "Cream Rinse:\t۱% W/W",
  "Vaginal Cream:\t۱%",
  "For Injection:\t۱۰ mg/۱۰ ml",
  "Injection: (Phosphate , Potassium)",
  "Powder: Each ۱۵ g Sachet Contains:",
  "Scored Tablets:\t۲۰۰ mg",
  "Iodine\t۰.۰۲۵ mg and",
  "۱۰: Levonorgestrel\t۰.۱۲۵ mg and\t\tEthinyl Estradiol\t۳۰ mcg",
  "For Injection: \t۲ mg/ml",
  "Injection: Quinine \t۲۵۰ mg/ml (as HCl)",
  "Film coated Tablets:\t۱۰ mg",
  "Elixir:\t\t۱۰ mg/۵ ml",
  "For Infusion:\t۵ mg/ml",
  "◇ Capsules:\t۲۰۰ I.U.",
  "◇ Soap:\t\t۵% (W/W)",
  "For I.V.Infusion:\t۱۰ mg/Vial",
  "Vaginal Gel:\t۱۰% (۸۰ g)",
  "For Injection:\t۰.۳ mg (۹.۶ million I.U.)/Vial",
  "◇ Cream: Diethyltoluamide\t۳۰-۴۰%",
  "For Injection: Cloxacillin \t۵۰۰ mg/Vial",
  "Capsules:\t۲ mg",
  "Tables: \t\t۲۵ mg",
  "For Oral Suspension: \t۲۵۰ mg (۴۰۰۰۰۰ U) /۵ ml (as Potassium)",
  "Coated Tablets:\t۲۵ mg",
  "Gel:\t\t۱.۲۳% (as Acidulated Phosphate)",
  "Folic Acid\t۱ mg and",
  "Powder for suspension: ۲۰ mg/mL (۱۰۰ mg/۵ mL)",
  "Injection Solution:\t۲۰ mg/۱۰ ml",
  "Syrup:\t\t۱ mg/۵ ml",
  "Capsules: \t۲۰۰ mg",
  "Sterile Eye Drops:\t۰.۱۳%",
  "Injection:\t۲۰ mg/ml",
  "◇ For Injection:\t۱.۵ g (as Sodium Salt)",
  "Topical Cream: Phenytoin Sodium\t۱%",
  "◇ Cream:\t۰.۰۲۵-۰.۰۷۵%",
  "Vaginal Douche:\t۱۰%",
  "Injection:\t۱ mg/ml",
  "Topical Ointment:\t۱۰۰۰۰۰ Units/g",
  "Film Coated Tablets: \t۲۰ mg",
  "Injection:\t۶۰% (۲۰ml)",
  "Injection: Neostigmine Methyl Sulfate \t۲.۵ mg/ml (۱,۵ ml)",
  "Injection Solution:\t۲۰%",
  "Chlorpheniramine Maleate\t۲.۵ mg and",
  "Tablets or Capsules:  ۳۷.۵ mg",
  "Scored Tablets:\t۴۰ mg",
  "Sterile Eye Drops: Epinephrine \t۱%",
  "Gel:\t\t۲% (as HCl)",
  "Vaginal Tablets: \t۵۰۰ mg",
  "Scored Tablets:\t۰.۲ mg",
  "Injection:\t۰.۲۵% (۱۰,۲۰ ml)",
  "Delayed Release Tablets:\t۲۵۰ mg",
  "Scored Tablets: \t۲۵۰ mg",
  "Amiloride HCl\t۵ mg (as Dihydrate) and",
  "◇ Film Coated Tablets:\t۲۵۰ mg(as Axetil)",
  "KCl\t۰.۰۷۵%",
  "Hydrocortisone Acetate\t۰.۵ %",
  "Tablets:  ۵ mg",
  "Injection:\t۱۵۰ mg/ml (۲ ml)",
  "Menthol \t۱۰%",
  "Scored Tablets:\t۲۵ mcg",
  "Vaginal Suppositories:\t۲۰۰ mg",
  "Tablets:\t۳۰۰۰ FCC U",
  "Injection: \t۱۰۰۰۰ KIU/۱ml",
  "Powder for inhalation:  ۲۰۰ mcg/metered inhalation",
  "Injection:\t۲۵۰ mg/ml",
  "Solution: ۲۰ mg/ml",
  "Injection:\t۴۰۰۰ U/ml (۰.۵ml)",
  "Aerosol:",
  "Sulfamethoxazole\t۱۰۰ mg and",
  "Tablets:\t۲ mg",
  "Phenylephrine HCl\t۱۵ mg and",
  "Scored Film Coated Tablets:\t۴۰ mg",
  "Ophthalmic Ointment: Retinol Palmitate \t۲۵۰ I.U./g",
  "Capsules: ۱۲.۵ mg",
  "Dextrose\t۲۳ mg",
  "Injection: Nandrolone Phenpropionate\t۲۵ mg/۱ ml",
  "For Injection:\t۵۰ mg/Vial",
  "Scored Tablets (Forte): \t۲۵۰ mg",
  "Capsules: ۲۰۰ mg",
  "Capsules:\t۳۰۰ mg",
  "0",
  "Acetaminophen\t۳۰۰ mg and",
  "Scored Tablets:\t۲۵۰ mg",
  "Extended-release capsules: ۳۷.۵ mg",
  "Topical Gel:\t۵%",
  "Injection: \t۱۰ mg/ml (۱ml, ۵ml)",
  "Injection:\t۴ g/۱۰ ml",
  "Syrup:\t\t۲۵۰ mg/۵ ml (۲۴۰ ml)",
  "Aerosol:\t۱ mg/Dose",
  "Clavulanic Acid\t۳۱.۲۵ mg/Sachet(as Potassium Salt)",
  "Sterile Eye Drops:\t۰.۲۵%",
  "Lotion (Sunscreen):",
  "Codeine Phosphate\t۱۰ mg",
  "Implant: ۱۰.۸ mg",
  "Tablets:\t۲.۵ mg",
  "For Injection: Spectinomycin\t۲ g/Vial",
  "Vitamin B۶\t۱۰ mg and",
  "Injection:\t۱۰ mg/ml (۲ ml)",
  "Tablets: \t\t۲۵۰ mg",
  "Tablets:\t۱۵ mg",
  "Atropine Sulfate\t۰.۰۲۵ mg",
  "Para aminobezoic Acid\t۵% w/w and",
  "Tablets:\t \t۴ mg",
  "Injection:\t۸۰ U/ml",
  "KH۲PO۴\t۲۲۵ mg/ml and",
  "Folic Acid\t۰.۴ mg and",
  "For Injection:\t۱۰۰۰ U/Vial + Diluent",
  "Injection Solution: ۱۰ mg/mL",
  "KH۳O۳\t۳۱۵ mg",
  "Sustained Release Film Coated Tablets:\t۲۴۰ mg",
  "* Amilase ۶۰۰۰ FIP.U+Lipase ۱۰۵۰۰ FIP.U+Protease ۶۰۰ FIP.U",
  "Infusion :\t۰.۵% (۵, ۵۰۰ ml)",
  "Ethinyl Estradiol\t۰.۰۳۵ mg",
  "Syrup:\t\t۱۵ mg/۵ ml",
  "Powder:\t۱۵۰ mg",
  "Fluticason Propionate \t۵۰ mcg",
  "Injection:\t۱۰۰ mg/۲ ml",
  "For Injection:\t۲۰ mg",
  "Nasal / Oral Inhaler:\t۱۰ mg/Container",
  "Calcium\t۲.۱۲ mg and",
  "Tablets: ۱۰ mg",
  "Injection:\t۱۵ mg/۳ ml (as HCl)",
  "Sublingual Tablets or Capsules:\t۶.۵ mg",
  "Paromomycin\t۱۵ g and",
  "Inhaler:\t۵۰ mcg / Dose",
  "NaCl\t۴.۵۱ g and",
  "Injection: Neostigmine Methyl Sulfate \t۰.۵ mg/ml",
  "Capsules: \t۴۰ mg",
  "Effervescent Tablets:\t۳۲۵ mg",
  "Polymyxin B Sulfate\t۱۰۰۰۰ U/۱ ml and",
  "For Injection:\t۸۰ mcg/Vial",
  "Suspension: Chloramphenicol \t۱۵۰mg/۵ml (as Palmitate) (۶۰ml)",
  "Injection:\t۴ mg/ ۲ ml",
  "Sustained Release Tablets: Quinidine Bisulfate\t۲۵۰ mg",
  "Tablets: \t۲۰۰ mg",
  "Zinc Sulfate\t۰.۲۵ % W/V",
  "Calcium Lactate Gluconate\t۲.۹۴ g and",
  "Simethicone\t۴۰ mg",
  "Capsules or Tablets: Cloxacillin \t۵۰۰ mg",
  "Infusion Solution:\t۲۴۰ mg I/ml (۱۰, ۲۰, ۵۰, ۱۰۰, ۲۰۰ ml)",
  "Injection:\t۳۰۰۰۰۰ U",
  "Film Coated Tablets:\t۸ mg",
  "Pediatric Suspension: Clindamycin \t۷۵ mg/۵ ml (as Palmitate HCl) (۱۰۰ml)",
  "Capsules for Inhalation:\t۱۲ mcg",
  "Injection: \t۱۸۰ mcg/ml",
  "Powder for inhalation:  ۴۰۰ mcg/metered inhalation",
  "Injection:\t۱۵۰ mg/ml",
  "Injection: Phenobarbital \t۲۰۰ mg/ml",
  "For Injection:\t۰.۵ mg",
  "Enteric Coated Tablets:\t۵۰۰ mg",
  "(Penicillin G Potassium\t۲۰۰۰۰۰ Units/Vial and",
  "Injection: Phenytoin Sodium \t۲۵۰ mg/۵ ml",
  "For Injection:\t۰.۴ mg",
  "Film Coated Tablets:\t۲۰ mg",
  "Powder:\t۵ g/Sachet",
  "CaCl۲ , ۲H۲O\t۰.۰۴۸%",
  "Vitamin A Palmitate\t۱۵۰۰ I.U./ml and",
  "Suppositories:\t۴۰۰ mg",
  "Syrup: \t\t۵۰۰ mg/۵ ml",
  "Tablets: ۱۰۰۰ mg",
  "Liquid:\t۱۲۵ mg/۵ ml",
  "Solution For Injection: ۲۵ mg/mL",
  "Vitamin B۲\t۱.۲۵ mg and",
  "Injection:\t۵ mg/ml",
  "BULK (Phosphate, Sodium Dibasic) (Na۲HPO۴)",
  "Film Coated Tablets:\tEq. To ۵۰۰ mg Fe++",
  "Pediatric Tablets:",
  "Injection: Pentazocine \t۳۰ mg/ml (as Lactate)",
  "Retention Enema:\t۱۰۰ mg/۶۰ ml",
  "Controlled Release Capsules or Tablets:\t۱۰۰ mg",
  "Topical Ointment: Tacrolimus\t۰.۰۳% (as Monohydrate)",
  "Injection Solution:\t۱۰ mg/ml (۵, ۱۵ ml)",
  "Injection Solution:\t۱۰۰۰ mg/۱۰ ml",
  "Injection: \tMethotrexate* \t۵۰ mg/۵ ml (as Sodium Salt)",
  "Tablets:\t \t۲ mg",
  "Injection: \t۸۰ mg/ml",
  "Powder for Suspension:\t۱۳۵ g/Sachet",
  "For Suspension:\t۵۰ g",
  "Tablets: Quinine \t۱۰۰ mg (as HCl)",
  "Tablets:\t۰.۱ mg",
  "Solution for Subcutaneous Injection: ۱۰۰ units/mL",
  "Topical Ointment:\t۲%",
  "Injection: Tetracosactrin ۱ mg/ml (as Acetate Zinc Phosphate Complex)",
  "Film Coated Tablets:\t۱۰ mg",
  "Vaginal Tablets: \t۱۰۰ mg",
  "Enteric Coated Tablets:\t۲۵۰ mg",
  "Injection Solution:\t۱۰ Units/ml",
  "Injection:\t۱۰%",
  "Ophthalmic Ointment\t۱%",
  "Capsules:\t۴۰ mg",
  "Injection:\t۳۰۰ mg/۲۰ ml",
  "◇ Film Coated Tablets:\t۱۲۵ mg(as Axetil)",
  "For Injection:\t۵۰۰ U/Vial + Diluent",
  "Lidocaine\t۲.۵% and",
  "Injection:\t۱۰۰ mg/۲ ml (as Sodium Succinate)",
  "Infusion Solution:\t۱۰۰۰ ml",
  "Theophylline Anhydrous\t۱۵۰ mg/۱۵ ml and",
  "Injection Solution: ۲ mg/mL (۱۰۰, ۲۰۰, ۳۰۰ mL)",
  "Scored Tablets:\t۵۰۰ mg",
  "Cream: ۱۳.۹ %",
  "For Suspention:\t۲۵۰ mg/۵ml (۱۰۰ml)",
  "Enteric Coated Tablets:\t۲۰۰ mg",
  "Film coated Tablets:\t۵ mg",
  "Myrtillus anthocyanosides\t۱۰۰ mg and",
  "Injection Solution:\t۱۰ mg/ml",
  "Injection Solution:\t۲۵ mg / ۰.۵ ml (۰.۵ و ۱و ۱۰ ml)",
  "Scored Film Coated Tablets:\t۱۵۰ mg",
  "Injection Solution:\t۵۰ mg / ۰.۵ ml (۰.۵ و۱و۱۰ ml)",
  "For I.V.Infusion:\t۱۵۰ mg/Vial",
  "Plaster (۱۲ cm × ۱۸ cm):\tCapsaicin (۰.۰۲۵%-۰.۰۸%)",
  "Capsules:\t۱ g (EPA ۱۸% + DHA ۱۲%)",
  "Chewable Tablets:\t۲۰۰mg",
  "NaH۳O۳\t۳۵۰ mg and",
  "Film Coated Tablets: Doxycycline\t۱۰۰ mg (as Hyclate)",
  "Vitamin B۶\t۰.۱۲۵ mg and",
  "Double Scored Tablets:\t۴ mg",
  "coated Tablets:\t۱۰۰ mg",
  "Shampoo:\t۱%",
  "Scored Film Coated Tablets:\t۳ mg",
  "LH\t۷۵ IU",
  "Capsules: ۱۰۰ mg",
  "Carbidopa\t۲۵ mg(as Monohydrate)",
  "For Suspension Drops:\t۱۰۰۰۰۰ Units/ml",
  "Injection:\t۲.۵% (۲ ml)",
  "Topical suspension: ۰.۹% W/W (۱۲۰ mL bottles)",
  "Injection Solution:  ۵ mg/ml",
  "Injection:\t۰.۳ mg/ml",
  "Capsules: \t۸۰ mg",
  "Scored Coated Tablets:\t۰.۱۲۵ mg",
  "◇ Soap:\t\t۲%",
  "Capsules or Tablets:\t۵۰ mg",
  "Tablets:\t۳۰۰ mg",
  "Lumefantrine \t۱۲۰ mg",
  "Injection:\t۲۵۰۰ I.U./۰.۲ ml",
  "Capsules: ۱۵ mg",
  "Phenylephrine HCl\t۵ mg and",
  "Sublingual Tablets:\t۰.۴ mg",
  "◇ Gel: Triamcinolone\t۰.۱%",
  "Sterile Eye Drops:\t۱۰%",
  "For Suspension:\t۲۵۰ mg/۵ ml (۱۰۰ ml)",
  "Powder",
  "Injection:\t۱۰۰ mg/۱۰ ml",
  "For Injection:\t۱۰۰ mcg/Vial",
  "Injecton:\t۱۰۰ mg/ml",
  "Ergotamine Tartrate\t۱ mg and",
  "Injection Solution:\t۱ mg/ml",
  "Diatrizoate Sodium\t۷.۹%)",
  "Tablets:\t۰.۶۲۵ mg",
  "Tablets: \t\t ۱۵ mg",
  "Epinephrine\t۱/۱۰۰۰۰۰",
  "Magnesium\t۰.۲۵ mg and",
  "Oral Drops:\t۶۰ mg/ml",
  "Naloxone HCl\t۲ mg",
  "Topical Ointment:\t۲۰%",
  "◇ Tablets:\t۵.۴ mg",
  "Pseudoephedrine HCl\t۷.۵ mg and",
  "Topical Solution:\t۱%",
  "Coated Tablets:\t۶.۵ mg",
  "Oral Suspension:\t۶۰ mg/ml (۱۲۰ ml)",
  "Tablets:\t۱.۲۵ mg",
  "Lidocaine HCl\t۱% (۱۰ mg/ml) and",
  "Amoxicillin\t۲۵۰ mg/۵ ml (as Trihydrate) and",
  "Chewable Tablets: \t۱ g",
  "Film Coated Tablets:\t۴۰ mg",
  "For Injection: Nafcillin\t۱ g/Vial (as Sodium Salt)",
  "For Injection:\t۵۰۰ U/Vial",
  "Injection:\t۵۰ mg Phospholipids/ ۱.۲ml",
  "Capsules or Tablets:\t۱۰۰ mg",
  "Immediate-Release Tablets: ۰.۵ mg",
  "Cetrimide \t۱۵% and",
  "◇ Stick: Diethyltoluamide\t۳۰-۴۰%",
  "Injection Solution:\t۵ Units/ml (۱ml)",
  "◇ Lotion:\t۵% (W/W or W/V)",
  "Tablets: ۵ mg",
  "Phenytoin Sodium\t۱۰۰ mg and",
  "Tablets: \t\t۱۰ mg",
  "Capsules:\t۲۵ mg",
  "Capsules: \t۳۰۰ mg",
  "MgCl۲ , ۶H۲O\t۰.۰۳%",
  "Capsules or Tablets:\t۲۵۰ mg",
  "Topical Cream: Triamcinolone\t۰.۱%",
  "Injection:\t۵ mg/۱۰ ml",
  "Urea\t۱۰ g/ ۱۰۰ g",
  "Extended-Release Tablets: ۳ mg",
  "Capsules:",
  "Coated Tablets:\t۲۵۰ mg",
  "Suspension: \t۳۰ g/۲۴۰ ml",
  "Injection:\t۵۵۰ mg/ml (۲۷۰ mg I/ml)",
  "مقدار ۱.۶g کلیندامایسین پالمیتات هیدروکلراید، تقریباً معادل ۱g کلیندامایسین است.",
  "Tablets: ۵۰۰ mg",
  "Topical Cream:\t۰.۲%",
  "Powder for ۱۰۰۰ ml Oral Solution:",
  "Injection:\t۳۰۵ mg/ml (۱۵۰ mg I/ml)",
  "Soap:\t\t۱% (۱۰۰ g) PH=۵.۵",
  "Injection:\t۲۰۰ mg/۵ ml",
  "Buprenorphine HCl\t۲ mg and",
  "NaCl\t۳.۵ g and",
  "Droperidol\t۲۵ mg/۱۰ ml and",
  "Mo\t۰.۱ mg and",
  "Injection Solution:\t۴۰۰ mg/۴ ml",
  "For Injection: Cephalothin \t۱ g/Vial",
  "Codeine Phosphate\t۱۰ mg/۵ ml",
  "Vitamin D\t۴۰۰ I.U. and",
  "Cl -\t۱۰۹ mEq/Lit",
  "For Injection: Cefepime \t۵۰۰ mg/Vial (as HCl)",
  "Tablets: ۱ mg",
  "I.V.Infusion:\t۱۰ mg/۲۰ ml",
  "For Injection:\t۱۰۰ mg (as Sodium Succinate)",
  "Film Coated Tablets: \t۴۰ mg",
  "Penicillin G Procaine\t۳۰۰۰۰۰ Units/Vial",
  "Tablets:\t۷۵ mg",
  "Immediate-Release Tablets: ۱ mg",
  "Padimate D\t۳.۲% w/w",
  "Buprenorphine HCl\t۸ mg and",
  "Topical Solution: ۱.۵%",
  "Tablets: ۲۵ mg",
  "(Soluble Insulin Aspart \t\t۳۰% and",
  "Vitamin B۶\t۲ mg and",
  "Infusion:\t۵۰ mg/ml (۱, ۵ ml)",
  "Tablets: ۱۵۰ mg (as Fumarat)",
  "Tablets: ۲۰ mg",
  "For Injection:\t۲۵۰ mg/Vial",
  "Film Coated Tablets:\t۲۵۰ mg (as HCl)  Film Coated Tablets:\t۵۰۰ mg (as HCl)",
  "Suspension: \t۵۰ mg/۵ ml",
  "Injection:\t۱۵۰ mg/۲۵ ml",
  "For Injection:\t۵۰۰ mg(as Sodium Salt)",
  "Topical Ointment:\t۰.۰۳%",
  "Benzoyl Peroxide\t۵%",
  "◇ Aerosol: \t۲۵۰ mcg/Dose",
  "Injection:\t۵ mg/۰.۵ ml",
  "Solution for I.V. Infusion:",
  "Injection:\t۲ ml",
  "Solution For Inhalation:\t۲۰ mg/ml",
  "Injection:\t۳۷۰ mg I/ml (۵۰, ۱۰۰ ml)",
  "Effervescent Tablets:\t ۶۰۰ mg",
  "Tablets:\t\t۵ mg",
  "(Levodopa ۵۰mg and Benserazide HCl ۱۲.۵mg)",
  "Oral Drops:",
  "For Suspention:\t۱۲۵ mg/۵ml (۱۰۰ml)",
  "Injection:\t۰.۲ mg/ml",
  "Film Coated Tablets:\t۵۰ mg",
  "Oral Drops: Metoclopramide \t۶۰ mg/۱۵ ml",
  "Tablets: ۸۰ mg",
  "Injection:\t۵۰ IU/ ml",
  "Medroxyprogesterone Acetate\t۲۵ mg and",
  "Tablets: ۵ mg (As Benzoate)",
  "Salbutamol\t۱۰۰ mcg and",
  "Injection:\t۲ mg/۲ ml",
  "Extended-Release Tablets: ۲۰۰ mg (as Pamoat)",
  "Solution for injection: ۱۰۰ mg/mL",
  "Injection: Calcium [as Gluconate] \t۱۰% (۱۰ ml)",
  "Injection: \t۲۵۰ mcg/ml (۳ml)",
  "Injection:\t۵۰ mg I/ml (۱۰۰ ml)",
  "For Injection:\t۲ g/Vial",
  "Capsules:\t۱۰۰ mg",
  "Scored Tablets:\t۲.۵ mg",
  "Scored Film Coated Tablets:\t۲۰۰ mg",
  "Capsules:۱۱۰ mg",
  "Spray:\t\t۲۵۰ mcg/Dose",
  "Sustained Release:\t۲۰۰ mg",
  "For Injection:\t۶۰۰ mg/Vial",
  "Solution for IV Administration:  ۱ mg/ml (۵ mg/۵ ml)",
  "Tablets:\t۷.۵ mg (as Phosphate ۱۳.۱۵ mg)",
  "◇ Plaster:\t۴۰ mg",
  "Scored Tablets:\t۱.۵ mg",
  "Elixir:\t\t۴ mg/ ۵ ml",
  "Injection:\t۲۰۰ mg / ۲ ml",
  "Capsules: \t۴۰۰ mg",
  "Injection:\t۱ mg/ml (۵ ml)",
  "Tablets: ۲۰۰ mg (as Fumarat)",
  "Clavulanic Acid \t۱۲۵ mg (as Potassium Salt)",
  "Capsules: \t۱۰۰ mg",
  "Topical Cream:\t۲%",
  "Trimethoprim\t۸۰ mg",
  "مقدار ۱.۵g اریترومایسین لاکتوبیونات تقریباً معادل ۱g اریترومایسین است.",
  "For Injection: ۸۰ mg/vial",
  "Injection: Fentanyl\t۰.۵ mg/۱۰ ml (as Citrate)",
  "Sterile Solution For Irrigation:\t۱.۵%",
  "Injection:\t۲۰۰۰۰ KIU/۱ml",
  "Tablets: Biperiden HCl \t۲ mg",
  "Granules",
  "Phenylpropanolamine HCl\t۲۰ mg",
  "Topical Ointment:\t۳۰%",
  "Film Coated Tablets: \t۳۰۰ mg",
  "Powder for injection: ۷۵ mg/vial",
  "Film Coated Tablets:  ۱۴ mg",
  "Injection Solution:\t۱ mg/ml (۰.۱% Norepinephrine)",
  "Cream Shampoo:\t۲%",
  "For Injection:\t۸۰۰۰۰۰ Units/Vial",
  "For Injection (Intraocular):\t۱%",
  "Film Coated Tablets:\t۴ mg",
  "Sterile Eye Drops:",
  "Sublingual Tablets:\t۵ mg",
  "Injection Solution:\t۵۰ mg/ml (۱۰ ml)",
  "For Suspension:\t۱۰۰ mg/۵ ml (as Dihydrate) (۳۰ ml)",
  "Film Coated Tablets:\t۲.۵ mg",
  "Ethinyl Estradiol\t۳۰ mcg",
  "Rectal Tube:\t۱۰ mg",
  "Chlordiazepoxide HCl\t۵ mg",
  "Injection Solution:\t۰.۲ mg/ml",
  "Coated Tablets:\t۱۰ mg",
  "Tablets:\t۳۲۵ mg",
  "Ointment:\t۲%",
  "Tablets:\t\t۲۰۰ mg",
  "Film Coated Tablets:\t۱ mg",
  "Tablets:\t۶۰ mg",
  "Nasal Drops:\t۰.۵%",
  "Tablets: ۴۰ mg",
  "Capsules: ۲۵ mg",
  "I.V.Infusion:\t۵۰۰ mg/۱۰۰ ml",
  "For Oral Suspension:\t۱۲۵ mg/۵ml (۱۰۰ml)",
  "Implants:\t۶× ۳۶ mg",
  "Sustained Release Tablets:\t۱۰۰ mg",
  "Capsules or Coated Tablets:\t۲۵۰ mg",
  "Powder for Inhalation:\t۹ mcg",
  "For Injection:\t۰.۸ mg (as Acetate)",
  "Articaine Hydrochloride \t۴% and",
  "Sustained Release Capsules:\t۳۰ mg",
  "Injection:  ۲۰ mg/mL",
  "Delayed Release Tablets: \t۴۰ mg (as Sodium Sesquihydrate)",
  "Felypressin\t۰.۰۳ I.U.(۰.۵۴ mcg/ml)",
  "Syrup:\t\t۲ mg/۵ ml (۶۰ ml)",
  "◇ Tablets:\t۵ mg",
  "Injection:\t۰.۵ mg/ml",
  "For Injection: Daunorubicin \t۲۰ mg/vial",
  "Scored Tablets:\t۲ mg",
  "◇ Tablets:\t۵ mEq",
  "For Injection: Azathioprine \t۵۰ mg/Vial (as Sodium Salt)",
  "Naphazoline HCl\t۰.۰۵% and",
  "For Pediatric Suspension:\t۵۰ mg/Sachet",
  "Powder for Injection: ۱۰۰ mg/vial",
  "Injection:\t۵ mg/ml (۲ ml)",
  "For Injection: Ampicillin \t۵۰۰ mg/ Vial (as Sodium Salt)",
  "Sulbactam \t۰.۵ g/Vial (as Sodium)]",
  "Salicylic Acid\t۱۶.۷ % and",
  "Syrup:\t\t۱g/۱۰ml",
  "Capsules: ۵۰ mg",
  "Co- Amoxiclav ۳۷۵",
  "MnSO۴ ۴H۲O\t۲.۰۵ mg and",
  "Benzocaine\t۱۰ mg",
  "Tablets:\t۲۵۰ mg",
  "Scored Tablets:\t۱ mg",
  "Injection Solution:\t۰.۴ mg/ml",
  "Scored Film Coated Tablets:\t۵۰ mg",
  "Pseudoephedrine HCl\t۳۰ mg/۵ ml",
  "Tablets: Quinidine Sulfate\t۲۰۰ mg",
  "Lyophilized Powder for Injection: ۲۵۰ mcg/vial",
  "Injection:\t۴۶۹ mg/ml",
  "Injection:\t۲ mg/ml",
  "Capsuls: ۵۰ mg",
  "Sterile Eye Drops:\t۰.۰۶%",
  "Tablets: ۱۰۰ mg",
  "Topical Gel:\t۱%",
  "For Injection:\t۵۰mg/Vial",
  "Collodion\tQs to ۱۰۰ %",
  "Injection Solution:  ۲۰ mg/mL",
  "Premixed infusion: ۴۰۰ mg/۲۵۰ mL ۰.۸% NaCl",
  "۱g پروپاستامول معادل ۰.۵g پاراستامول (استامینوفن) است.",
  "Infusion Solution:\t۳۰۰ mg I/ml (۱۰, ۲۰, ۵۰, ۱۰۰, ۲۰۰ ml)",
  "Vaginal Gel:\t۲ mg/۲.۵ ml",
  "Injection:\t۳ ml",
  "Trimethoprim\t۸۰ mg/۵ ml",
  "Scored Tablets:\t۰.۰۵ mg",
  "Injection Solution:",
  "Inositol\t۱۲.۵ mg and",
  "Double Scored Tablets:\t۳۰۰ mg",
  "Oral Solution:\t۱۲۰ mg/۵ ml",
  "Suspension:",
  "◇ Capsules:\t۱۲۰ mg",
  "For Injection: Ampicillin \t۱ g/ Vial (as Sodium Salt)",
  "Capsules:\t۰.۴ mg",
  "Injection: \t۳۶۰ mcg/ml (۰.۵ ml)",
  "For Injection: Cloxacillin \t۲۵۰ mg/Vial",
  "Injection: \tMethotrexate* \t۲۵ mg/ml (as Sodium Salt)",
  "Injection:\t۵۰ mg/ml (۲ ml)",
  "Injection: \t۱ g/ml (۱.۵ ml)",
  "Vitamin A Acetate\t۱۲۵۰ I.U. and",
  "Oral Solution:\t۱۲۵ mg/۵ ml",
  "For Oral Suspension: \t۱۲۵ mg (۲۰۰۰۰۰ U) /۵ ml (as Potassium)",
  "Tablets:\t\t۱۰ mg",
  "Injection: Leucovorin Ca \t۱۰ mg/ml(۳ ml)",
  "Coated Tablets: Trifluoprazine \t۵ mg",
  "Infusion:\t۲۵۰ mg/۲۵ ml",
  "Guaifenesin\t۹۰ mg/۱۵ ml",
  "For Injection:\t۲۰۰ mg",
  "Scored Film Coated Tablets:\t۱ mg",
  "Injection:\t۵ mg/۲ ml",
  "Lotion:\t۱%",
  "For Injection:\t۴ mg",
  "Sodium Na+ \t۱۵۴ mmol and",
  "Solution for Injection: ۱۰۰ units/mL",
  "For Infusion Solution:\t۲۰ mEq/۱۰ ml",
  "Powder for Inhalation: \t۴.۵ mcg",
  "Ethinyl Estradiol\t۰.۰۳ mg",
  "Immediate-Release Tablets: ۵۰ mg",
  "Tablets:\t۲۱۰ mg",
  "Injection:\t۱۰ mg/۲ ml",
  "For Continuous I.V.Infusion:\t۲%(۵۰ml)",
  "Microcoated Tablets:\t۵۰۰ mg",
  "For Injection:\t۱۲۰۰۰۰۰ Units/Vial",
  "Cyclizine Hce\t۱۵۰ mg",
  "Naloxone HCl\t۰.۵ mg",
  "For Injection:\t۱۰۰ mg/Vial",
  "For Injection:\t۵۰۰ mg/Vial",
  "For Injection: Piperacillin \t۲ g/Vial",
  "Teblets:\t۲۵۰ mg",
  "Ophthalmic Ointment:\t۰.۱%",
  "Oral Solution:",
  "For Injection: Penicillin G \t۱۰۰۰۰۰۰ Units/Vial (as Potassium Salt)",
  "Injection:\t۵ ml",
  "Coated Tablets: Pyrvinium\t ۵۰ mg",
  "Chewable Tablets:\t۴۰۰mg",
  "Plaster:\t۵ mg/۲۴ h",
  "Injection Solution:\t۱۵۰ mg/۳ ml",
  "Diphenhydramine HCl\t۱۲.۵ mg/۵ ml and",
  "Zinc Oxide\t۱۴%",
  "Extended-Release Tablets: ۱۵۰ mg (as Fumarat)",
  "Tablets: ۱۰۰ mg (as Fumarat)",
  "Tablets: ۰.۲۵ mg",
  "Immediate-Release Tablets: ۰.۲۵ mg",
  "Capsules: ۴۵ mg",
  "Tablets: \t۶.۲۵ mg",
  "Sterile Eye Drops:\t۴%",
  "Scored Film Coated Tablets:\t۲ mg",
  "Sodium Citrate\t۵۰ mg/۵ ml and",
  "Infusion: ۵۰%* (Eq.to ۵۰g Dextrose/۱۰۰ml) (۵۰,۵۰۰ ml)",
  "Phenylpropanolamine HCl\t۱۵ mg",
  "Ophthalmic Ointment:\t۵%",
  "Tablets: \t۱۰۰ mcg",
  "Oral Solution: \t۵۰۰ mg/۵ ml",
  "Lactic Acid\t۱۶.۷ % and",
  "Tablets: Prazosin \t۱ mg",
  "(Penicillin G Potassium\t۱۰۰۰۰۰ Units/Vial and",
  "Injection:\t۶۲۵ mg/ml (۳۲۰ mg I/ml)",
  "Injection: \t۲ mg/ml",
  "Topical Solution: \t۱۰ mg/ml",
  "Immediate-Release Tablets: ۰.۱۲۵ mg",
  "Infusion: ۱۰%* (Eq.to ۱۰g Dextrose/۱۰۰ml) (۵۰۰,۱۰۰۰ml)",
  "Scored Coated Tablets:\t۱۰۰ mg",
  "Cetylpyridinium Chloride \t۲ mg and",
  "Capsules:\t۳۰ mg",
  "Sublingual Tablets or Capsules:\t۲.۵ mg",
  "Powder for Solution: ۶۰ mg/۵ ml",
  "Tablets: Piperazine Hexahydrate \t۵۰۰ mg (as Citrate or Phosphate)",
  "Suspension: Phenytoin Sodium\t۳۰ mg/۵ ml",
  "Injection\t۵۰ mg Iron/ml (۲ ml)",
  "Tablets:\t۷۷.۲۵ mg",
  "◇Patch:\t\t۰.۲ mg/۲۴ h",
  "(Eq. to ۵۰۰mg Ca/Eff.Tab)",
  "[Ampicillin\t۲ g/Vial (as Sodium) and",
  "Iron (as Ferrous Sulfate)\t۱۸ mg and",
  "هر قرص جوشان حاوی ۵۰۰mg فسفر است.",
  "Nasal Ointment: Mupirocin\t۲% (as Calcium)",
  "Oral Drops:\t۱۲۵ mg (۲۵ mg Iron) /ml",
  "Tablets:  ۱۰ mg",
  "Ca Pantothenate\t۱۱.۶ mg and",
  "Disposable Injector:\t۱ mg/ml (۲ ml )",
  "Plaster: Estradiol S.R. \t۴ mg/۱۰ cm۲ (۵۰ mcg/۲۴ h)",
  "Methyl Salicylate\t۱۵% and",
  "Vitamin A\t۲۵۰۰۰ I.U. and",
  "Tablets: \t۱ mg",
  "Capsules:۱۵۰ mg",
  "Liquid:\tEPA ۱۸% + DHA ۱۲%",
  "Ca++\t۴.۵ mEq/Lit and",
  "Coated Tablets: Trifluoprazine \t۱ mg",
  "Powder for inhalation:  ۱۰۰ mcg/metered inhalation",
  "Sterile Ophthalmic- Otic- Nasal Drops:\t۰.۱%",
  "Sorbitol \t۱۳.۴ g",
  "Surgical Scrub:\t۷.۵% (۲۵۰,۱۰۰۰,۳۸۰۰ ml)",
  "Injection:\t۲۸۷ mg/ml",
  "Infusion: ۵%* (Eq.to ۵g Dextrose/۱۰۰ml) (۵۰۰,۱۰۰۰ml)",
  "Topical Cream:\t۰.۰۳%",
  "Oral Suspension:\t۲۵ mg/۵ ml",
  "Sodium Chloride\t۳۵۰.۷ mg and",
  "Coated Tablets:\t۲۰ mg",
  "Lotion:\t۰.۰۵%",
  "Chewable Tablets:\t۱۰۰ mg",
  "Injection: ۱۵ mg/mL",
  "Injection: Dexamethasone Phosphate \t۸ mg/۲ ml (as Disodium Salt)",
  "◇ Lotion:",
  "Scored Tablets:",
  "Suppositories:\t(۷۰% w / w) ۲ g",
  "Coated Tablets: Trifluoprazine \t۲ mg",
  "For Suspension:\t۵۰۰ mg/۶ ml (۱۲۰ ml)",
  "Solution for Injection: ۲۰ mg/mL",
  "Infusion :\t۰.۴۵% (۵۰۰, ۱۰۰۰ ml) (۱/۲ Normal Saline)",
  "Tablets:  ۸۰۰ mg (as Carbonate or Hydrochloride)",
  "For Infusion:\t۱۰ mg/۵۰ ml",
  "Zinc Oxide\t۳۰%",
  "Solution for Injection:  ۵ mg/ml",
  "Sustained Release Tablets:\t۴۰۰ mg",
  "Tablets: \t۱.۵ mg",
  "Beta-Carotene\t۵ mg",
  "Atovaquone \t۲۵۰ mg and",
  "Tablets: Neostigmine Bromide \t۱۵ mg",
  "Tretinoin\t۰.۰۱%",
  "Suppositories:\t۵۰ mg",
  "Spray Suspension(Nasal): ۰.۰۵%",
  "Injection:\t۴.۵ million IU/ml",
  "Coated Tablets:\t۵۰ mg",
  "۲۱: Norgestrel\t۰.۳ mg and",
  "Tablets:\tMethotrexate \t۲.۵ mg (as Sodium Salt)",
  "(Diatrizoate Meglumine\t۶۶% and",
  "Clavulanic Acid \t۳۱.۲۵ mg/۵ ml (as Potassium Salt)",
  "Injection: Chloroquine\t۱۵۰ mg/۵ ml (as Phosphate)",
  "Rifampin\t۱۲۰ mg",
  "Chlorpheniramine Maleate\t۲ mg/۵ ml and",
  "Tablets:\t۱۸۰ mg",
  "Topical Gel:\t۰.۰۵%",
  "◇ Tablets: Pentazocine \t۵۰ mg",
  "For Injection:\t۱g (as Sodium Salt)",
  "Injection Solution: \t۱۰% (۳۰۰ ml)",
  "Sulfamethoxazole\t۴۰۰ mg and",
  "Enteric Coated Tablets:\t۵ mg",
  "For Injection: Cyclophosphamide \t۲۰۰ mg+ Diluent",
  "Sterile Eye Drops:\t۵ %",
  "Topical Cream: \t۵%",
  "Tablets: ۱۰ mg",
  "Syrup:\t\t۱۰ mg/۵ ml",
  "Topical Gel:\t۰.۶%",
  "Acetaminophen\t۱۶۲.۵ mg and",
  "Capsules or Tablets:\t۵۰۰ mg",
  "Syrup:\t\t۱۰ g/۱۵ ml",
  "Oral Drops:\t۴ mg/ml",
  "در هر میلی‌لیتر از محلول I :",
  "Concentrated Solution:",
  "Triamterene\t۵۰ mg and",
  "Topical Cream:\t۵%",
  "◇ Capsules:\t۲۵ mg",
  "Tooth Paste:\t۱۰%",
  "◇ I.V. Infusion:\t۶% (۵۰۰ ml)",
  "Tablets:۱ mg",
  "Film Coated Tablets:\t۰.۲۵ mg",
  "Acetaminophen\t۸۰ mg",
  "Topical Ointment:\t۱۰%",
  "مقادیر موجود در اشکال دارویی، براساس سفالکسین بدون آب است.",
  "مقدار ۲۰۰ mg آمینوفیلین آبدار تقریباً معادل ۱۵۸mg آمینوفیلین بدون آب است.",
  "Oral Solution: \t۲۰ mg/۵ ml",
  "Scored Tablets:\t۱۰ mg",
  "Sterile Eye Drops:\t۲۰ mg/ml",
  "Suspension:\t۵۰ mg/۱۵ ml",
  "مقدار ۱.۲g کلیندامایسین فسفات، تقریباً معادل ۱g کلیندامایسین است.",
  "KCl\t۱.۵ g and",
  "Tablets: \t۱۲۵ mg",
  "Elixir:\t\t۱۲.۵ mg/۵ ml",
  "Pediatric Suppositories:\t۵ mg",
  "Nasal Spray\t۶۴ mcg/Dose",
  "Levodopa\t۱۰۰ mg and",
  "For Inhalation:\t۲۵۰ ml/Flacon",
  "Sored Tablets:\t۸۰ mg",
  "For Injection: Piperacillin \t۱ g/Vial",
  "Solution For Nebulisation:\t۲۰ mg/۲ ml",
  "Capsules:\t۲۰۰ mg",
  "Film Coated Tablets: \t۵۰۰ mg (۸۰۰۰۰۰ U) (as Potassium)",
  "Injection: Fluphenazine Decanoate\t۲۵ mg/ml",
  "Enteric Coated Tablets:\t۴۰۰ mg",
  "Tablets: ۷۵۰ mg",
  "Film coated Tablets:\t۱ mg",
  "Film Coated Tablets:\t۲۰۰ mg",
  "۶: Levonorgestrel\t۰.۰۵ mg and",
  "Coated Tablets:\t۶۰ mg",
  "Injection:\t۱ g/Vial",
  "Oral Solution:\t۷۰%",
  "Injection:\t۰.۲۵ mg/ml (۲ ml)",
  "Lotion: \t۱۰% (W/W or W/V)",
  "Tablets:\t۵۰ mg",
  "Scored Film Coated Tablets:\t۴۰۰ mg",
  "Sterile Ophthalmic Solution: (۱۵ ml, ۱۸ ml, ۵۰۰ ml)",
  "For Injection: ۴۰ mg/Vial",
  "Sustained Release Tablets:\t۸۰ mg",
  "Capsules: ۲۰ mg",
  "Capsules or Tablets:\t۱۵۰ mg",
  "◇ Vaginal Cream:\t۲%",
  "Film Coated Tablets:\t۳۰ mg",
  "مقدار ۱.۰۶g سفالوتین سدیم، معادل ۱g سفالوتین است.",
  "Tablets: \t\t۲ mg",
  "Sublingual Tablets or Capsules:\t۰.۴ mg",
  "(Oxidized Glutathione)",
  "for Infusion\t۵۰ mg",
  "Pediatric Suppositories:\t(۷۰% w / w) ۱ g",
  "Penicillin G Procaine\t۶۰۰۰۰۰ Units/Vial)",
  "Tablets: \t ۲۰۰ mg",
  "Iron Reduced\t۱۰ mg and",
  "Sustained Release Tablets:\t۳۰ mg",
  "Injection Solution: ۵ mg/mL",
  "For Injection: Methyl Prednisolone \t۵۰۰ mg/Vial +Diluent",
  "◇ Capsules:\t۴۰۰ I.U.",
  "Injection:\tMethotrexate* \t۵ mg/ml (as Sodium Salt)",
  "Injection: Biperiden Lactate \t۵ mg/ml",
  "Clavulanic Acid \t۲۸.۵ mg/۵ ml (as Potassium Salt)",
  "Injection:\t۲۰۰ mg/ml (۱,۵ ml)",
  "Tablets: ۵۰۰ mg (Phosphate, Potassium Monobasic)",
  "◇ Ear Drops:\t۰.۳ %",
  "Injection Solution:\t۵۰ mg/ml (۲, ۱۰, ۲۰ ml)",
  "For Injection:\t۳۰ mg",
  "Injection:\t۰.۵% (Spinal)",
  "Supension:\t۳۲۰ mg/۵ ml",
  "For Injection:\t۵۰۰ U(Concentrated)",
  "Topical Cream: Clobetasol \t۰.۰۵%",
  "Coated Tablets:\t۴۵۰ mg",
  "Injection solution:\t۱۰ mg/ml",
  "For Infusion:\t۳۰ mg/۵ ml",
  "Powder for injection: ۱۵۰ mg/vial",
  "Injection:\t۲۵۰ mg/۵ ml",
  "Film coated Tablets: \t۱۵۰ mg",
  "Injection Solution:\t۵۰ mg/۱ ml",
  "Injection: Clindamycin \t۱۵۰ mg/ml (as Phosphate)",
  "◇ Capsules:\t۱۰۰ I.U.",
  "ZnSO۴ ۷H۲O\t۲.۳ mg and",
  "Calcium Pantothenate\t۱.۲۵ mg and",
  "Scored Coated Tablets:\t۱۳۵ mg",
  "Capsules:\t۳ mg",
  "For Injection:\t۳.۲ mg (as Acetate)",
  "◇ For Injection:\t۲۵۰ mg (as Sodium Salt)",
  "Film Coated Tablets: Ranitidine \t۱۵۰ mg",
  "Casules:\t\t۲۰۰ mg",
  "Phenylpropanolamine HCl\t۱۲.۵ mg/۵ ml and",
  "For Suspension:\t۱۲۵ mg/۵ ml (۱۰۰ ml)",
  "Solution for Irrigation:\t۰.۹%",
  "Vitamin B۲\t۵ mg and",
  "For Injection:\t۱۰۰۰ mg",
  "Solution:\t۵۰ % (۵۰ ml/Vial)",
  "Injection: Ketamine\t۵۰۰ mg/۱۰ ml",
  "Tablets: \t\t۲۰ mg",
  "Oral Drop:\t۴%",
  "Ophthalmic Ointment:\t۰.۵%",
  "Vitamin D\t۲۰۰ I.U.",
  "Vitamin B۱۲\t۶ mcg and",
  "Folic Acid\t۴۰۰ mcg",
  "Spray:\t \t۲۵/۱۲۵",
  "For I.V.Infusion:\t۵۰ mg/Vial"
]