# Generated by Django 4.1.1 on 2022-09-10 07:56

from django.db import migrations, models
import django.db.models.deletion
import unixtimestampfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="option", old_name="option", new_name="text",
        ),
        migrations.RenameField(
            model_name="question", old_name="question", new_name="text",
        ),
        migrations.RenameField(
            model_name="useranswersubmit", old_name="submitter", new_name="user",
        ),
        migrations.RemoveField(model_name="option", name="quest",),
        migrations.AddField(
            model_name="challenge",
            name="created_at",
            field=unixtimestampfield.fields.UnixTimeStampField(
                auto_now_add=True, default=None
            ),
        ),
        migrations.AddField(
            model_name="option",
            name="question",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="options",
                to="core.question",
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="questions",
            field=models.ManyToManyField(to="core.question"),
        ),
        migrations.AlterField(
            model_name="question",
            name="right_option",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="right_option",
                to="core.option",
            ),
        ),
    ]
