# Generated by Django 4.1.1 on 2022-09-10 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_rename_option_option_text_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="question", old_name="right_option", new_name="right_answer",
        ),
        migrations.RenameField(
            model_name="useranswersubmit", old_name="answer", new_name="option",
        ),
    ]
