# Generated by Django 4.1.1 on 2022-09-13 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_challenge_private_alter_challenge_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="invitation_code",
            field=models.CharField(default="", max_length=10),
        ),
    ]
