# Generated by Django 4.1.1 on 2022-09-23 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_challenge_invitation_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="Level",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="", max_length=255)),
                ("icon", models.ImageField(default="", upload_to="levels")),
                ("min_points", models.IntegerField(default=0)),
            ],
        ),
    ]
