# Generated by Django 4.1.1 on 2022-10-23 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_questionreport"),
    ]

    operations = [
        migrations.AlterField(
            model_name="option", name="text", field=models.CharField(max_length=5000),
        ),
    ]
