# Generated by Django 4.1.1 on 2022-10-23 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_option_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="is_available",
            field=models.BooleanField(default=True),
        ),
    ]
