# Generated by Django 4.1.1 on 2022-09-17 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("drug", "0003_prescription_verified_prescriptionitem_pharmacist_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="prescription", old_name="verified", new_name="labeled",
        ),
    ]
