# Generated by Django 4.1.1 on 2022-09-17 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("drug", "0005_prescriptionitem_verifed"),
    ]

    operations = [
        migrations.AddField(
            model_name="prescriptionitem",
            name="prescription",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="drug.prescription",
            ),
        ),
    ]
