# Generated by Django 4.1.1 on 2022-09-17 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("drug", "0006_prescriptionitem_prescription"),
    ]

    operations = [
        migrations.RenameField(
            model_name="prescriptionitem", old_name="verifed", new_name="verified",
        ),
    ]
