# Generated by Django 4.1.1 on 2022-10-19 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drug", "0008_remove_prescriptionitem_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="prescriptionitem",
            name="trading_name",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
