# Generated by Django 4.1.1 on 2022-10-20 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drug", "0009_prescriptionitem_trading_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="prescriptionverification",
            name="comment",
            field=models.CharField(default="", max_length=500, null=True),
        ),
    ]
