# Generated by Django 4.1.1 on 2022-10-20 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drug", "0010_prescriptionverification_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prescriptionitem",
            name="trading_name",
            field=models.CharField(default="", max_length=255, null=True),
        ),
    ]
