block_1 = ["Oxygen", "Nortriptyline", "Ganirelix", "Zinc", "Fluvoxamine", "Clozapine", "Triptorelin", "Risperidone",
           "Testosterone propionate", "Linezolid", "Oxcarbazepine",
           "Progesterone", "Fluoxetine", "Eplerenone", "Dextromethorphan", "Moclobemide", "Penicillamine",
           "Chlorthalidone",
           "Digoxin", "Panthenol", "Quazepam", "Mirtazapine", "Gonadorelin", "Ethosuximide", "Terbinafine", "Urea",
           "Rotigotine",
           "Sulpiride", "Danazol", "Enoxaparin", "Thiamine", "Clonazepam", "Phenobarbital", "Pantothenic acid",
           "Melatonin",
           "Triamterene", "Phenol", "Ethinylestradiol", "Adenosine", "Choline", "Spironolactone", "Glucosamine",
           "Desipramine",
           "Cholecalciferol", "Estradiol", "Propafenone", "Valsartan", "Enalapril", "Prazosin", "Ethanol",
           "Valproic acid",
           "Amitriptyline", "Gabapentin", "Tryptophan", "Aprepitant", "Riboflavin", "Tamoxifen", "Pyrazinamide",
           "Buserelin",
           "Losartan", "Duloxetine", "Opicapone", "Tiagabine", "Meperidine", "Vitamin E", "Methionine", "Safinamide",
           "Amlodipine", "Creatine", "Trazodone", "Metoclopramide", "Haloperidol", "Chlorpromazine", "Folic acid",
           "Atomoxetine",
           "Testosterone undecanoate", "Pimozide", "Istradefylline", "Ropinirole", "Water", "Lysine", "Trifluoperazine",
           "Reserpine", "Selegiline", "Pramipexole", "Furosemide", "Talc", "Vitamin D", "Isoniazid", "Vigabatrin",
           "Biperiden",
           "Oxandrolone", "Tadalafil", "Ketamine", "Codeine", "Venlafaxine", "Pregnenolone", "Zonisamide",
           "Cabergoline",
           "Goserelin", "Fondaparinux", "Bumetanide", "Methylphenidate", "Lisinopril", "Metolazone", "Bromocriptine",
           "Cyproterone acetate", "Amisulpride", "Phenytoin", "Levetiracetam", "Aliskiren", "Allopurinol",
           "Levonorgestrel",
           "Morphine", "Escitalopram", "Lamotrigine", "Deferasirox", "Tocopherol", "Cocaine", "Colchicine",
           "Benperidol",
           "Lithium citrate", "TryptophanThiram", "Fluphenazine", "Tramadol", "Desvenlafaxine", "Dutasteride",
           "Amiloride",
           "Nilotinib", "Levodopa", "Magnesium", "Dydrogesterone", "Methyldopa", "Oxymetholone", "Desmopressin",
           "Carbidopa",
           "Amantadine", "Fosphenytoin", "Nicorandil", "Lynestrenol", "Pergolide", "Carbamazepine", "Olanzapine",
           "Methadone",
           "Caffeine", "Epinephrine", "Ofloxacin", "Ascorbic acid", "Cholestyramine", "Sertraline", "Isocarboxazid",
           "Heparin",
           "Lopinavir", "Telmisartan", "Paroxetine", "Buspirone", "Thioridazine", "Warfarin", "Trihexyphenidyl",
           "Perazine",
           "Nifedipine", "Promazine", "Histamine", "Perphenazine", "Indapamide", "Iron", "Cetrorelix", "Eprosartan",
           "Clobazam",
           "Tizanidine", "Lithium carbonate", "Amphetamine", "Tranylcypromine", "Potassium", "Amoxapine", "Sildenafil",
           "Tetrabenazine", "Maprotiline", "Saquinavir", "Finasteride", "Terazosin", "Bupropion", "Acetylcholine",
           "Estrone",
           "Pregabalin", "Chlorothiazide", "Norepinephrine", "Tolcapone", "Testosterone", "Quetiapine", "Fluconazole",
           "Voriconazole", "Benserazide", "Clopidogrel", "Citalopram", "Cholesterol", "Dabigatran",
           "Estradiol valerate",
           "Clomipramine", "Primidone", "Drospirenone", "Aripiprazole", "Mianserin", "Trimipramine", "Norgestrel",
           "Cyproheptadine", "Raloxifene", "Neon", "Niacin", "Ciprofloxacin", "Apomorphine", "Topiramate", "Doxazosin",
           "Captopril", "Dexpanthenol", "Hydrochlorothiazide", "Imipramine", "Doxepin", "Ranolazine", "Griseofulvin",
           "Dopamine", 'leuprorelin',
           "Cimetidine", "atenolol", 'bisoprolol', 'carvedilol', 'labetalol', 'metoprolol', 'nebivolol', 'propranol',
           'hydralazine', 'minoxidil', 'Clonidine', 'diltiazem', 'verapamil', 'nimodipine', 'losartan', 'NITROGLYCERIN',
           'ISOSORBIDE ']
block_2 = ["Lactulose", "Mizolastine", "Prucalopride", "Pheniramine", "Triamcinolone", "Ondansetron", "Thymol",
           "Acrivastine", "Estazolam", "Dexlansoprazole", "Aluminium", "Phenobarbital", "Pyridostigmine", "Buclizine",
           "Alprazolam", "Famotidine", "Clarithromycin", "Bleomycin", "Acetazolamide", "Mechlorethamine", "Midazolam",
           "Water", "Chlorpromazine", "Bortezomib", "Rabeprazole", "Terbutaline", "Ephedrine", "Olanzapine",
           "Rivastigmine", "Dimenhydrinate", "Calcipotriol", "Terfenadine", "Pimecrolimus", "Levodopa",
           "Levocetirizine", "Procainamide", "Fosaprepitant", "Succinylcholine", "Stearic acid", "Memantine",
           "Rupatadine", "Ciprofloxacin", "Triazolam", "Codeine", "Physostigmine", "Trimethoprim", "Tacrine",
           "Dimethyl fumarate", "Sorbitol", "Roflumilast", "Ceftriaxone", "Acetylcysteine", "Mitoxantrone",
           "Magnesium sulfate", "Dexamethasone", "Bromhexine", "Cimetidine", "Erythromycin", "Ipratropium", "Biguanide",
           "Methylprednisolone", "Clemastine", "Ethanol", "Oleic Acid", "Salbutamol", "Diroximel fumarate",
           "Pramlintide", "Urea", "Guaifenesin", "Metoclopramide", "Acyclovir", "Methylnaltrexone", "Promethazine",
           "Digoxin", "Vancomycin", "Buspirone", "Theophylline", "Bilastine", "Pantoprazole", "Pentobarbital",
           "Doxylamine", "Zaleplon", "Naphazoline", "Domperidone", "Tramadol", "Cisplatin", "Promazine", "Flunisolide",
           "Eszopiclone", "Azelaic acid", "Palmitic Acid", "Cyclizine", "Magnesium", "Prednisolone", "Chlordiazepoxide",
           "Naloxegol", "Zopiclone", "Clonazepam", "Nicotine", "Sildenafil", "Carbamazepine", "DopamineIron",
           "Amiodarone", "Linoleic acid", "Secobarbital", "Tiotropium", "Montelukast", "Neostigmine", "Lorazepam",
           "Fluticasone propionate", "Docusate", "Ketotifen", "Hydroxyzine", "Desonide", "Perphenazine", "Oxaliplatin",
           "Fluticasone", "Haloperidol", "Cyclophosphamide", "Ofloxacin", "Granisetron", "Hydroquinone",
           "Pseudoephedrine", "Dicyclomine", "Carboplatin", "Bisacodyl", "Formoterol", "Scopolamine", "Paclitaxel",
           "Acetylcholine", "Naltrexone", "Cinnarizine", "Fexofenadine", "Opium", "Netupitant", "Zinc", "Perazine",
           "Pyridoxine", "Ketamine", "Palonosetron", "Dimethicone", "Budesonide", "Phenytoin", "Dextromethorphan",
           "Glycerin", "Piracetam", "Tacrolimus", "Donepezil", "Mannitol", "Phenylephrine", "Lansoprazole", "Oxazepam",
           "Nizatidine", "Linaclotide", "Tadalafil", "Vincristine", "Esomeprazole", "Clidinium", "Diazepam",
           "Chlorpheniramine", "Magnesium hydroxide", "Loratadine", "Favipiravir", "Magnesium citrate", "Colchicine",
           "Cetirizine", "Omeprazole", "Histamine", "Carbinoxamine", "Prochlorperazine", "Choline", "Tetracycline",
           "Zolpidem", "Nedocromil", "Gefitinib", "Cyproheptadine", "Metformin", "Remdesivir", "Mebeverine",
           "Pentoxifylline", "Salmeterol", "Ferrous fumarate", "Oxygen", "Aprepitant", "Cysteine", "Aminophylline",
           "Propantheline", "Zafirlukast", "Diphenhydramine", "Fluorouracil", "Meclizine", "Dopamine", "Fingolimod",
           "Levothyroxine", "Galantamine"]
block_3 = ["Cisplatin", "Fluorouracil", "Cefotaxime", "Gadopentetic acid", "Niclosamide", "Gemifloxacin", "Terbinafine",
           "Squalene", "Azlocillin", "Iohexol", "Triazolam", "Griseofulvin", "Mezlocillin", "Ethambutol",
           "Dihydroergotamine", "Itraconazole", "Curcumin", "Caspofungin", "Clotrimazole", "Diatrizoate", "Doripenem",
           "Nitrogen", "Vinorelbine", "Amitriptyline", "Albendazole", "Lindane", "Sulfisoxazole", "Ceftobiprole",
           "Vinblastine", "Gadolinium", "Tobramycin", "Cefazolin", "Piperazine", "Vancomycin", "Histamine", "Desonide",
           "Sulbactam", "Permethrin", "Nalidixic acid", "Ergosterol", "Nortriptyline", "Praziquantel", "Ofloxacin",
           "Urea", "Gadodiamide", "Ketoconazole", "Tinidazole", "Carbenicillin", "Voriconazole", "Phenobarbital",
           "Flucytosine", "Amikacin", "Warfarin", "Paromomycin", "Pyrimethamine", "Imipramine", "Nystatin",
           "Streptomycin", "Nafcillin", "Vincristine", "Cyclosporine", "Primaquine", "Iopromide", "Neomycin",
           "Ciprofloxacin", "Piperacillin", "Budesonide", "Cilastatin", "Metronidazole", "Ceftriaxone", "Penicillamine",
           "Isoniazid", "Levamisole", "Posaconazole", "Iopamidol", "Carbamazepine", "Pyrazinamide", "Fluorescein",
           "Rifampicin", "Meropenem", "Perazine", "Imipenem", "Cefotetan", "Pyrvinium", "Midazolam", "Acyclovir",
           "Mebendazole", "Fludrocortisone", "AztreonamTolnaftate", "Lincomycin", "Cefepime", "Amphotericin B",
           "Pentetic acid", "Ticarcillin", "Miconazole", "Fluconazole", "Meglumine", "Clobetasol", "Sulfamethoxazole",
           "Gadoteric acid", "Chloroquine", "Ampicillin", "Iodine", "Sulfadoxine", "Cisapride", "Procaine", "Ertapenem",
           "Natamycin", "Ergotamine", "Diphenhydramine", "Hydroxychloroquine", "Tazobactam", "Amoxicillin",
           "Trimethoprim", "Fluticasone", "Ivermectin", "Probenecid", "Fluorometholone", "Digoxin", "Barium sulfate",
           "Sulfadiazine", "Cholesterol", "Clavulanic acid", "Cephalexin", "Choline", "Metoclopramide", "Levofloxacin",
           "Iodixanol", "Phenytoin", "Deflazacort", "Triamcinolone"]
block_4 = ["Melphalan", "Pravastatin", "Hydroxychloroquine", "Travoprost", "Estradiol", "Clonazepam", "Mechlorethamine",
           "Alendronic acid", "Doxorubicin", "Calcium carbonate", "Fluorouracil", "Vincristine", "Temsirolimus",
           "Diazepam", "Zanamivir", "Cidofovir", "Vinblastine", "Brinzolamide", "Salicylic acid", "Ezetimibe",
           "Estramustine", "Raloxifene", "Sunitinib", "Leuprolide", "Acetaminophen", "Triptorelin", "Foscarnet",
           "Dactinomycin", "Goserelin", "Fluconazole", "Vitamin D", "Abacavir", "Betaxolol", "Strontium ranelate",
           "Zidovudine", "Vinorelbine", "Lactic acid", "Choline", "Cimetidine", "Quetiapine", "Timolol", "Etoposide",
           "Gemcitabine", "Valganciclovir", "Topotecan", "Cholic Acid", "Rosuvastatin", "Tipranavir", "Tolmetin",
           "Leucovorin", "Progesterone", "Amprenavir", "Lopinavir", "Stavudine", "Flutamide", "Peramivir", "Naproxen",
           "Mitomycin", "Lenalidomide", "Phenylephrine", "Chloroquine", "Olanzapine", "Chlorambucil", "Tyrosine",
           "Cetirizine", "Acyclovir", "Pomalidomide", "Sulindac", "Dihydroergotamine", "Thiotepa", "Pilocarpine",
           "Deoxycholic acid", "Anastrozole", "Methotrexate", "Dacarbazine", "Delavirdine", "Pitavastatin",
           "Cytarabine", "Bimatoprost", "Everolimus", "Ribavirin", "Rizatriptan", "Trifluridine", "Tromantadine",
           "Irinotecan", "RaloxifeneUrsodeoxycholic acid", "Penciclovir", "Helium", "Ketorolac", "Echothiophate",
           "Valaciclovir", "Efavirenz", "Diclofenac", "Oseltamivir", "Eribulin", "Erlotinib", "Piroxicam", "Celecoxib",
           "Latanoprost", "Fulvestrant", "Rimantadine", "Bicalutamide", "Nilutamide", "Omeprazole", "Caffeine",
           "Ribociclib", "Lutein", "Clonidine", "Amantadine", "Letrozole", "Bleomycin", "Lapatinib", "Simvastatin",
           "Sorafenib", "Temozolomide", "Docosanol", "Cladribine", "Lovastatin", "Sumatriptan", "Ritonavir",
           "Saquinavir", "Cyclophosphamide", "Benzalkonium", "Atorvastatin", "Vidarabine", "Idarubicin", "Indomethacin",
           "Meloxicam", "Ergotamine", "Nitrogen", "Didanosine", "Lamivudine", "Alprazolam", "Abiraterone", "Nilotinib",
           "Digoxin", "Ibuprofen", "Capecitabine", "Imatinib", "Brimonidine", "Fluoxymesterone", "Fludarabine",
           "Palbociclib", "Carmustine", "Indinavir", "Urea", "Exemestane", "Cisplatin", "Ranitidine", "Lomustine",
           "Sirolimus", "Famciclovir", "Docetaxel", "Buserelin", "Threonine", "Atazanavir", "Tamoxifen",
           "Fluorometholone", "Cabazitaxel", "Epirubicin", "Ibandronate", "Pemetrexed", "Oxaliplatin", "Remdesivir",
           "Zalcitabine", "Bortezomib", "Metipranolol", "Mefenamic acid", "Nelfinavir", "Apraclonidine", "Daunorubicin",
           "Levobunolol", "Olopatadine", "Zoledronic acid", "Paclitaxel", "Ganciclovir", "Idoxuridine", "Nevirapine",
           "Carboplatin", "Fluvastatin", "Thalidomide", "Carteolol"]
