# Generated by Django 4.1.1 on 2023-02-11 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("leitner", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Daroo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("clinicalAttentions", models.TextField(default="", null=True)),
                ("pregnancyCategory", models.TextField(default="", null=True)),
                ("tradeNames", models.TextField(default="", null=True)),
                ("contraindications", models.TextField(default="", null=True)),
                ("pregnancy", models.TextField(default="", null=True)),
                ("treatmentCategory", models.TextField(default="", null=True)),
                ("name", models.TextField(default="", null=True)),
                ("pharmacologyCategory", models.TextField(default="", null=True)),
                ("iranianGenericProducts", models.TextField(default="", null=True)),
                ("indications", models.TextField(default="", null=True)),
                ("pharmacoDynamics", models.TextField(default="", null=True)),
                ("interactions", models.TextField(default="", null=True)),
                ("sideEffects", models.TextField(default="", null=True)),
                ("breastFeeding", models.TextField(default="", null=True)),
                ("trainings", models.TextField(default="", null=True)),
            ],
        ),
        migrations.CreateModel(
            name="FlashCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.IntegerField(
                        choices=[
                            (1, 1),
                            (2, 2),
                            (3, 3),
                            (4, 4),
                            (5, 5),
                            (6, 6),
                            (7, 7),
                        ],
                        default=1,
                    ),
                ),
                (
                    "daroo",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="leitner.daroo",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
