# Generated by Django 4.1.1 on 2023-03-08 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("leitner", "0004_daroo_block_combined"),
        ("questionator", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="useranswer",
            name="daroo",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="leitner.daroo",
            ),
        ),
    ]
